package com.kt.controller;

import java.lang.reflect.Array;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.propertyeditors.CustomDateEditor;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.kt.bean.PMS;
import com.kt.bean.QCField;
import com.kt.dao.PMSEntryDAOImpl;

@Controller
public class PMSEntryController {

	@InitBinder
	public void initBinder(WebDataBinder binder){
		CustomDateEditor editor=new CustomDateEditor(new SimpleDateFormat("MM/dd/yyyy"), true);
		binder.registerCustomEditor(Date.class, editor);
	}//initBinder closed

	private PMSEntryDAOImpl PMSDao;
	

	@Autowired
	public void setPMSDao(PMSEntryDAOImpl pMSDao) {
		System.out.println("System inject"+pMSDao);
		PMSDao = pMSDao;
	}

	@RequestMapping(value="pmsEntry",method=RequestMethod.GET)
	public ModelAndView getPMSEntryPage(ModelMap modelMap) throws Exception{
		modelMap.addAttribute("PMSFormBackingObject",new PMS());
		modelMap.addAllAttributes(referenceData());
		return new ModelAndView("pmsEntry");
		
		
	}//close getRegisterPage

	@RequestMapping(value="check.form",method=RequestMethod.POST)
	public ModelAndView processRequest(@Valid @ModelAttribute("PMSFormBackingObject")PMS pms,BindingResult result)
	{
		if(result.hasErrors()){
			System.out.println("Pradeep");
			return new ModelAndView("pmsEntry");
		}else{
		
			int pmsId=0;
			try{
				pmsId=PMSDao.save(pms);
			}catch (Exception e) {
				System.out.println("Error at time of saving data");
			}
			return new ModelAndView("index","PMSFormBackingObject",pmsId);
		}
	}


	@SuppressWarnings("rawtypes")
	protected Map<String, Map<Integer, String>> referenceData() throws Exception {
		Map<String, Map<Integer, String>> referenceData = new HashMap<String, Map<Integer, String>>();
		Map<Integer,String> JobType = new LinkedHashMap<Integer,String>();
		Map<Integer,String> JobOwner = new LinkedHashMap<Integer,String>();
		Map<Integer,String> OfficeID = new LinkedHashMap<Integer,String>();
		Map<Integer,String> ProgressID = new LinkedHashMap<Integer,String>();
		Map<Integer,String> ExecID = new LinkedHashMap<Integer,String>();
		Map<Integer,String> StudyTypeID = new LinkedHashMap<Integer,String>();
		
		JobType.put(24,"Admin");
		JobType.put(4,"AP DP");
		JobType.put(5,"Business Solutions");
		JobType.put(11,"Charting");
		JobType.put(9,"Coding");
		JobType.put(18,"Dimensions");
		JobType.put(25,"DP");
		JobType.put(23,"Finance");
		JobType.put(3,"France DP");
		JobType.put(30,"Gurgaon DP");
		JobType.put(28,"Gurgaon Scripting");
		JobType.put(6,"Health Care");
		JobType.put(22,"HR");
		JobType.put(31,"IPM");
		JobType.put(19,"KMandTechnology");
		JobType.put(17,"Marketing Science");
		JobType.put(14,"MI");
		JobType.put(26,"Mobile Research");
		JobType.put(0,"Non-Billable");
		JobType.put(16,"Non-P&amp;G Germany");
		JobType.put(8,"P&amp;G");
		JobType.put(29,"Pune DP");
		JobType.put(27,"Pune Scripting");
		JobType.put(15,"QC");
		JobType.put(7,"RCL");
		JobType.put(13,"Research");
		JobType.put(10,"Scripting");
		JobType.put(20,"Tab Checking");
		JobType.put(12,"TechHome");
		JobType.put(1,"UK DP");
		JobType.put(2,"US DP");
		JobType.put(21,"World Panel");
		
//		--------------------------------------------------
		JobOwner.put(48,"A. PRAVEEN KUMAR");
		JobOwner.put(293,"ABDUL KAREEM MOHAMMED");
		JobOwner.put(1436,"ABDUL QUDDUS");
		JobOwner.put(381,"ABDUL WASEEM AHMED");
		JobOwner.put(2194,"ABHIJEET ARVIND MORE");
		JobOwner.put(1617,"ABHIRAJ DAS");
		JobOwner.put(2544,"Abhishek Anil Shivnikar");
		JobOwner.put(1830,"ABHISHEK ARVIND KARMARKAR");
		JobOwner.put(680,"ABHISHEK DARLA");
		JobOwner.put(1993,"ABIDA HAMEED");
		JobOwner.put(1395,"ADARSH KUMAR DINDIGALA");
		JobOwner.put(1678,"ADHVAITH P REDDY");
		JobOwner.put(2524,"ADITYA AMMU");
		JobOwner.put(1677,"ADITYA PAREEK");
		JobOwner.put(1848,"ADITYA SURESH DEOKAR");
		JobOwner.put(1029,"ADNAN BHANPURAWALA");
		JobOwner.put(1987,"AFREEN FATIMA");
		JobOwner.put(2354,"AFREEN UNNISA BEGUM");
		JobOwner.put(197,"AGNI RAJ SINGH");
		JobOwner.put(2550,"Ahmad Raza");
		JobOwner.put(662,"AHMED PASHA");
		JobOwner.put(1605,"AJANTHA PACKIASEELI NADAR");
		JobOwner.put(2320,"AJAY BALKRISHNA PENDHARKAR");
		JobOwner.put(1734,"AJAY JAIGUDE");
		JobOwner.put(2478,"AJAY KANAKAM");
		JobOwner.put(1716,"AJAY RAVINDRAN NAIR");
		JobOwner.put(1717,"AJINA ABDUL KHADER");
		JobOwner.put(2404,"AKASH ATHMARAM SHENOY");
		JobOwner.put(1635,"AKASH DAS");
		JobOwner.put(2457,"AKBAR VAJRALA");
		JobOwner.put(2151,"AKHIL KUMAR VISHWANATHAM");
		JobOwner.put(2537,"AKSHARA GUNDA");
		JobOwner.put(2462,"Akshata Kasar");
		JobOwner.put(2558,"Akshay Rajeshkumar Gupta");
		JobOwner.put(2426,"ALEKHYA DHANURI");
		JobOwner.put(2381,"ALEKHYA NAVUNDRU");
		JobOwner.put(2107,"Alok Ranjan");
		JobOwner.put(1764,"ALOK RANJAN RANA PRATAP SINGH");
		JobOwner.put(2203,"AMINAH NAUSHAD HUSSAIN");
		JobOwner.put(164,"AMIT NANDKUMAR MOHITE");
		JobOwner.put(1609,"AMIT RAMYAS YADAV");
		JobOwner.put(2406,"AMIT SHANKAR KHERADE");
		JobOwner.put(23,"AMIT SINGH");
		JobOwner.put(2057,"AMOL ASHOK MAHAJAN");
		JobOwner.put(1715,"AMOL JAYAWANT KADAM");
		JobOwner.put(1780,"AMOL SURESH NAVARKAR");
		JobOwner.put(2391,"AMOL VITHTHALRAO KADAM");
		JobOwner.put(1067,"AMRISH ASHOK PAWAR");
		JobOwner.put(2340,"AMRITANSHU KUMAR");
		JobOwner.put(591,"AMRUTHRAJ CHEKURI");
		JobOwner.put(2270,"ANAND MANIKANDAN");
		JobOwner.put(2384,"ANBURAJ CHINNAIYA");
		JobOwner.put(1637,"ANEESH KUMAR GIRISH");
		JobOwner.put(658,"ANGEL MATHEW");
		JobOwner.put(2207,"ANIKET ASHOK KUMTHEKAR");
		JobOwner.put(147,"ANIL ANTO");
		JobOwner.put(1201,"ANIL KUMAR OLLALA");
		JobOwner.put(1273,"ANIL KUMAR VENKATA NANDURI");
		JobOwner.put(2324,"ANIL PRAKASH MALI");
		JobOwner.put(1846,"ANIRUDDH GOUTAM PARANDE");
		JobOwner.put(2532,"ANISH MENON RANGHAT");
		JobOwner.put(2309,"ANJALI SANJAY CHUTTAR");
		JobOwner.put(2051,"Anjali Sinha");
		JobOwner.put(90,"ANJANI GEEDIMALLA");
		JobOwner.put(2545,"Ankit Ashok Agarwal");
		JobOwner.put(2159,"ANKITA TOSHNIWAL");
		JobOwner.put(1570,"ANKUR KISHAN AGRAWAL");
		JobOwner.put(1802,"ANKUSH MUKTAJI MUNJGUDE");
		JobOwner.put(2219,"ANUP KUMAR");
		JobOwner.put(56,"ANUP SETH");
		JobOwner.put(960,"ANUPAMA SAMANTARAY");
		JobOwner.put(2015,"ANUSHA GUNTAKA");
		JobOwner.put(2551,"Apeksha Ved");
		JobOwner.put(1399,"ARAVIND SUNAKANTI");
		JobOwner.put(2227,"ARAYALIN KEEZHIL RIJA DIVAKARAN");
		JobOwner.put(722,"ARCHANA DULAM");
		JobOwner.put(1818,"ARCHANA SACHIN MANE");
		JobOwner.put(2547,"Arpit Jaiswal");
		JobOwner.put(175,"ARPITHA VUPPADA");
		JobOwner.put(1991,"ARTI PERWARE");
		JobOwner.put(2170,"ARUN BHIMRAO BANGAR");
		JobOwner.put(1711,"ARUN KUMAR");
		JobOwner.put(595,"ARUN KUMAR GYARA");
		JobOwner.put(101,"ARUNA KUMAR MALINIDHI S.");
		JobOwner.put(2491,"ARUNA NAVUNDRU");
		JobOwner.put(1719,"ARUNA PRATIK TRIBHUVAN");
		JobOwner.put(2284,"ASHA CHINTHADA");
		JobOwner.put(1748,"ASHISH J CHAUDHARI");
		JobOwner.put(1548,"ASHISH JOSHI");
		JobOwner.put(2158,"ASHISH KUMAR SINGH");
		JobOwner.put(2382,"ASHISH PRAKASH UBRIANI");
		JobOwner.put(1849,"ASHOK BABURAO PAWAR");
		JobOwner.put(2121,"Ashok Matadin Saroj");
		JobOwner.put(2355,"ASHWINI KOTLA");
		JobOwner.put(2489,"ASHWITHA MARYADA");
		JobOwner.put(145,"ATUL KUMAR");
		JobOwner.put(790,"AVIK KUMAR SINHA");
		JobOwner.put(1315,"AVINASH CHANDRA");
		JobOwner.put(2075,"Avinash Chavan");
		JobOwner.put(2134,"Avinash Kisan Longadge");
		JobOwner.put(1756,"AVINASH TILEKAR");
		JobOwner.put(2312,"AYUSHI NARAYAN KHILWANI");
		JobOwner.put(598,"AZMATULLA KHAN LODHI");
		JobOwner.put(1183,"B NAGA SUNIL PRASAD");
		JobOwner.put(1564,"B. SAINATH");
		JobOwner.put(2333,"BABITA MISHRA");
		JobOwner.put(1178,"BABU RAO KARRI");
		JobOwner.put(1537,"BAGHBAN MAQMOOR RASTI");
		JobOwner.put(2318,"BALA JOSEPH VIKRAM ALLAM");
		JobOwner.put(121,"BALAJEE KADALI");
		JobOwner.put(1752,"BALAJI JANAKIRAMAN");
		JobOwner.put(1459,"BALAJI KODAVATI");
		JobOwner.put(1623,"BALRAJ G");
		JobOwner.put(2565,"BANITA SHARMA");
		JobOwner.put(8,"BASANTH KUMAR E. N.");
		JobOwner.put(2000,"BETA VIJAYA BINDU");
		JobOwner.put(2483,"BHAGYASHREE BANDEWAR");
		JobOwner.put(2425,"BHAGYASHRI K");
		JobOwner.put(2502,"Bhagyesh Bhausaheb Patil");
		JobOwner.put(2112,"Bhakta Vatsal Shukla");
		JobOwner.put(663,"BHANU CHANDER");
		JobOwner.put(333,"BHANU PRAKASH C.");
		JobOwner.put(227,"BHARATH GOLLA");
		JobOwner.put(578,"BHASKAR BAHAL");
		JobOwner.put(60,"BHASKAR BANDI");
		JobOwner.put(267,"BHASKAR KANCHARLA");
		JobOwner.put(1433,"BHASKER MADHANU");
		JobOwner.put(2276,"BHAVITHA BANTARAM");
		JobOwner.put(1281,"BHUPAL REDDY ERLADINNE");
		JobOwner.put(173,"BISHNU DAS");
		JobOwner.put(2363,"BISMA MOHD HANIF ANSARI");
		JobOwner.put(2214,"BRIDGET FRANCIS FERNANDES");
		JobOwner.put(1989,"BURLE LAKSHMI VARSHA");
		JobOwner.put(2291,"CHAITANYA SRAVANTHI KUCHIPUDI");
		JobOwner.put(270,"CHAITANYA VENKATESH NAKKA");
		JobOwner.put(2523,"CHAITRANAND CHAKRAWARTHY BURLA");
		JobOwner.put(385,"CHAKRAPANI SEVVA");
		JobOwner.put(2133,"Chakravarthy SLN Virivinti");
		JobOwner.put(2273,"CHANDANA PERMANLA PATIL");
		JobOwner.put(2495,"Chandane Gokul Atmaram");
		JobOwner.put(2127,"Chandra Jakkamsetti");
		JobOwner.put(336,"CHANDRA MOHAN PUDUCHERY");
		JobOwner.put(337,"CHANDRA SEKHAR DEEKONDA");
		JobOwner.put(2035,"Chandra Sekhar Vodde");
		JobOwner.put(2397,"Chandrakant Pawar");
		JobOwner.put(62,"CHANDRASEKHAR BALIVADA");
		JobOwner.put(170,"CHANDRASHEKHAR TECKWANI");
		JobOwner.put(2487,"CHATLAWAR ANUJA GANGARAM");
		JobOwner.put(64,"CHERUKURI BHAVANA");
		JobOwner.put(2074,"Cherupally Naveen Chandra");
		JobOwner.put(1737,"CHETAN MOHAN JAGTAP");
		JobOwner.put(171,"CHETAN PRABHAKAR SHETTY");
		JobOwner.put(1115,"CHETAN SRINIVAS GOVIND");
		JobOwner.put(2192,"CHHATRAPPA S BIRAJDAR");
		JobOwner.put(2504,"CHIDWILA KOTHURU");
		JobOwner.put(1195,"CHINMAYEE TAUDIA");
		JobOwner.put(2564,"CHIRAG SURESHBHAI CHAUHAN");
		JobOwner.put(1267,"CLEMENT CHRISTOPHER");
		JobOwner.put(360,"CYRILENE PAUL");
		JobOwner.put(1448,"DAMAYANTHI VENKATAUSHA VANGURI");
		JobOwner.put(279,"DAMODARA REDDY P.");
		JobOwner.put(191,"DANIEL JEEDIMARLA");
		JobOwner.put(2072,"DARSHAN GUJARATHI");
		JobOwner.put(1842,"DASHRATH BHIMA LOMTE");
		JobOwner.put(1837,"DATTATRAYA VASANT MOHOL");
		JobOwner.put(258,"DAVID CHANDRAN PAUL");
		JobOwner.put(2011,"DEBASISH SAHU");
		JobOwner.put(2486,"DEEPA NANJUNDA");
		JobOwner.put(2497,"Deepak Jain");
		JobOwner.put(2369,"DEEPAK KUMAR DIXIT");
		JobOwner.put(2132,"Deepak Venugopal");
		JobOwner.put(1626,"DEEPAK VERMA");
		JobOwner.put(2325,"DEEPALI VIHAL PATEL");
		JobOwner.put(2415,"DEEPIKA TIWARI");
		JobOwner.put(2048,"Devakee Rathour");
		JobOwner.put(2302,"DEVDATTA DINKAR JADHAV");
		JobOwner.put(2229,"DEVENDRA SINGH HUKUM SINGH");
		JobOwner.put(1553,"DEVIVARAPRASAD MUDDADA");
		JobOwner.put(777,"DEVLALNAIK VANKUDOTH");
		JobOwner.put(2307,"DEVYANI DEEPAK VYAVAHARE");
		JobOwner.put(1521,"DHANALAKSHMI SASUPALLI");
		JobOwner.put(2131,"Dhananjay Shiodas Chintanwar");
		JobOwner.put(2522,"DHANUNJAY REDDY K");
		JobOwner.put(1415,"DHARMENDRA KUMAR SINGH");
		JobOwner.put(1530,"DHEERAJ KUMAR DAMERA");
		JobOwner.put(1812,"DHEERAJ SHANKARLAL SONI");
		JobOwner.put(1838,"DINESH ANANT PAYER");
		JobOwner.put(1173,"DINESH KUMAR CHAVAN");
		JobOwner.put(299,"DINESH KUMAR H");
		JobOwner.put(1540,"DIPANKAR SAHA");
		JobOwner.put(2313,"DIVYA ANILRAO DANDALE");
		JobOwner.put(2505,"DIVYA KODELA");
		JobOwner.put(2146,"DIVYA MUSPATLA");
		JobOwner.put(2346,"DIVYA RANJANA");
		JobOwner.put(2351,"DIVYA SITOKE");
		JobOwner.put(1722,"DNYANESHWAR MADHUKAR SALVI");
		JobOwner.put(2050,"Dnyaneshwar Shahaji Wagh");
		JobOwner.put(2314,"DOLLY KAILASH AGRAWAL");
		JobOwner.put(1271,"DURGA PRASAD GUNDUBELLI");
		JobOwner.put(921,"DURGA SURESH");
		JobOwner.put(1019,"EADALA SRI SOWMYA");
		JobOwner.put(1245,"EDWARD DHANRAJ");
		JobOwner.put(2065,"EDWIN HARRY DSILVA");
		JobOwner.put(77,"ELIZABETH BURAGA");
		JobOwner.put(1974,"ENNALA DHIRAJ DASS");
		JobOwner.put(2043,"Enosh Raja Madanu");
		JobOwner.put(1967,"ESETTY CHETAN");
		JobOwner.put(2461,"ESHWAR KUMAR VADLA");
		JobOwner.put(1616,"FIROJ SULTAN SHAIKH");
		JobOwner.put(2167,"FRAVAK ROHINTON BHARUCHA");
		JobOwner.put(1068,"G CHANDRA SEKHAR");
		JobOwner.put(2003,"GADDAM JAYARAJU");
		JobOwner.put(340,"GANESH CHARY KANNAGI");
		JobOwner.put(1381,"GANESH HANUMANDLU KATTEKOLA");
		JobOwner.put(2114,"Ganesh Kumar Pradhan");
		JobOwner.put(954,"GANTALA NAVEEN KUMAR");
		JobOwner.put(1435,"GAURAV BAJPAI");
		JobOwner.put(1825,"GAURAV GUPTA");
		JobOwner.put(1160,"GAURAV KUMAR");
		JobOwner.put(2235,"GAURAV RABINDRANATH GHOSH");
		JobOwner.put(2033,"GAURAV SEKHANI");
		JobOwner.put(1828,"GAURAVKUMAR DATTATREYBHAI MORE");
		JobOwner.put(2292,"GAYATHRI SUBBA LAKSHMI GORTHI");
		JobOwner.put(2001,"GAYATRI KAVITARKIKA SIMHAM");
		JobOwner.put(2343,"GAYATRI WAMANRAO FUNDE");
		JobOwner.put(190,"GHOUSEUDDIN MOHAMMAD");
		JobOwner.put(84,"GIRI SRINIVAS A.");
		JobOwner.put(2370,"GITESH GANESH SAWANT");
		JobOwner.put(288,"GOPAL THOTA");
		JobOwner.put(2165,"GOVIND SRINATH SAGAR");
		JobOwner.put(1246,"GOWTHAM YETURU");
		JobOwner.put(151,"GURU KEERTHI SAGAR C.");
		JobOwner.put(1980,"HANDE SHABBIR ALI");
		JobOwner.put(1434,"HANUMANTHA RANGA RAO SOMAVARAPU");
		JobOwner.put(185,"HANUMANTHA RAO DIYYA");
		JobOwner.put(1238,"HARI BABU VELISHOJU");
		JobOwner.put(2359,"HARI KRISHNA REDDY SARIPALLI");
		JobOwner.put(343,"HARI KRISHNA REDDY V.");
		JobOwner.put(2380,"HARI PRASAD NELLURI");
		JobOwner.put(276,"HARIGOPAL REDDY MALIGI");
		JobOwner.put(2477,"HARINATH REDDY SIRUMALA");
		JobOwner.put(1406,"HARISH KUMAR V");
		JobOwner.put(1676,"HARISH MEDI");
		JobOwner.put(1235,"HARSHA CHANDRA YOGA PURINI");
		JobOwner.put(2519,"HARSHA MANI KANTA YELURI");
		JobOwner.put(2506,"HARSHA PERUPALLY");
		JobOwner.put(2283,"HARSHALI BABAN MATTE");
		JobOwner.put(2423,"HARSHITHA BOBOLU");
		JobOwner.put(1538,"HEMA BINDU RATHOD");
		JobOwner.put(2140,"HEMANT ACHYUTE PAREKH");
		JobOwner.put(2492,"HIMA BINDU MIKKILI");
		JobOwner.put(143,"HONEY GUPTA");
		JobOwner.put(388,"HRISHIKESH CHITNIS");
		JobOwner.put(1785,"IAN ALPHONSO");
		JobOwner.put(118,"INDRA MOHAN NARAKULLA");
		JobOwner.put(1619,"ISHAN NAGESH RAO");
		JobOwner.put(1174,"J CHINNA MADDILETI");
		JobOwner.put(2108,"Jacob Thekkethala George");
		JobOwner.put(676,"JAGDEEP SINGH BEDI");
		JobOwner.put(2344,"JAGRUTI MAHAPATRO");
		JobOwner.put(2429,"JAHIDUR RAHMAN");
		JobOwner.put(2416,"JANANI SANTHANAM");
		JobOwner.put(1694,"JAYA PRAKASH REDDY PENUMALLI");
		JobOwner.put(2290,"JAYASREE PERUMALLA");
		JobOwner.put(2356,"JAYESH BIND");
		JobOwner.put(656,"JAYESH PATEL");
		JobOwner.put(2554,"Jayesh Sunil Atmani");
		JobOwner.put(230,"JEEDI AARON PRANEETH");
		JobOwner.put(1247,"JEEVA SANTOSH G");
		JobOwner.put(1769,"JEEVAN LILBAHADUR THAPA");
		JobOwner.put(2202,"JEGANATHAN RAMANOUDJAN");
		JobOwner.put(2215,"JENNIFER RUPERT MOTI");
		JobOwner.put(2263,"JITENDRAKUMAR RAMJATAN YADAV");
		JobOwner.put(1805,"JITESH JAYANTILAL SHAH");
		JobOwner.put(2224,"JITHIN KOSHY JOSE");
		JobOwner.put(2097,"JONATHAN JOSHUA NAGELLI");
		JobOwner.put(2145,"JYOTHI KUMARI");
		JobOwner.put(2561,"JYOTSNA KUMARI");
		JobOwner.put(1853,"K S VARGHESE");
		JobOwner.put(784,"K V V DEEPAK");
		JobOwner.put(1697,"K.SUPRITHA");
		JobOwner.put(373,"KADARI SRINIVAS");
		JobOwner.put(1975,"KALASHIKA RAHUL SAI");
		JobOwner.put(2378,"KALAVIKAS KOLLOJU");
		JobOwner.put(2441,"KALINDI DASHRATH PAWAR");
		JobOwner.put(1796,"KALPESH GANDHI");
		JobOwner.put(390,"KALYAN CHAKRAVARTHI K.");
		JobOwner.put(2188,"KALYANI DILIP KALE");
		JobOwner.put(908,"KALYANI SRIVARI");
		JobOwner.put(2144,"KAMAL RAJ");
		JobOwner.put(144,"KAMALJEET DOGRA");
		JobOwner.put(1735,"KAMATA PRASAD PRAJAPATI");
		JobOwner.put(1409,"KAMLESH KUMAR SHRIWASTAW");
		JobOwner.put(2233,"KANGUJAM KENEDY SINGH");
		JobOwner.put(2066,"KANIZA MUSTAFA RAMPURAWALA");
		JobOwner.put(1832,"KAPIL BHAVSAHEB PATIL");
		JobOwner.put(2410,"Kapil Gala");
		JobOwner.put(52,"KARNATI SRINIVAS");
		JobOwner.put(730,"KAUSHIK MODAK");
		JobOwner.put(2073,"KAVITA JOSHI");
		JobOwner.put(851,"KAVITHA GADDAM");
		JobOwner.put(826,"KAVITHA PUTIGAMPU");
		JobOwner.put(2329,"KEERTHI KANDARI");
		JobOwner.put(2149,"KEERTHI SAGAR GADHAR");
		JobOwner.put(1081,"KEERTHIKA GODUGU");
		JobOwner.put(1757,"KETAKI VIDYADHAR GHATE");
		JobOwner.put(2372,"KETAN VILAS GAIDHANI");
		JobOwner.put(1982,"KEVIN BENHUR");
		JobOwner.put(392,"KHAJA RAHAMAN MOHIUDDIN");
		JobOwner.put(1408,"KHUSHAL DAS KHAJURIA");
		JobOwner.put(949,"KIRAN KUMAR BANDI");
		JobOwner.put(2205,"KIRAN KUMAR N R");
		JobOwner.put(1801,"KIRAN MAHADEV ANPAT");
		JobOwner.put(217,"KIRAN PALACHARLA JOGA BHASKAR");
		JobOwner.put(17,"KIRAN PRASAD GOTTIPATI");
		JobOwner.put(324,"KIRANKUMAR THANDURI");
		JobOwner.put(2177,"KIRTHI KUMAR AKKAPEDDY");
		JobOwner.put(2119,"Komal Subhash Mangaonkar");
		JobOwner.put(1833,"KOMAL SUNIL YADAV");
		JobOwner.put(1220,"KRANTHI KUMAR MAYDARAPU");
		JobOwner.put(1295,"KRISHNA CHAITANYA MUNNANGI");
		JobOwner.put(2172,"KRISHNA CHANDAR KANDULA");
		JobOwner.put(1713,"KRISHNA KISHORE ANUMULA");
		JobOwner.put(396,"KRISHNA RAO E. V.");
		JobOwner.put(2432,"KRISHNAKUMAR DHANDAPANI");
		JobOwner.put(2014,"KRISHNAPRATAP BRIJBHUSHAN CHAUHAN");
		JobOwner.put(2045,"Kumar Vivek");
		JobOwner.put(2129,"Kunal Singh");
		JobOwner.put(354,"KUSAM RAMA NARASIMHA REDDY");
		JobOwner.put(1762,"KUSHAL SANJAY DIWATE");
		JobOwner.put(398,"LAKSHMAN PURIHELLA T.");
		JobOwner.put(2136,"Lakshmi Badimala");
		JobOwner.put(1439,"LAKSHMI GAYATHRI APPIKONDA");
		JobOwner.put(1099,"LAKSHMI NARESH YADAV BANDI");
		JobOwner.put(1534,"LAKSHMI POOJYA NVN");
		JobOwner.put(2330,"LALITH KUMAR KANUGULA");
		JobOwner.put(2153,"LALITHYA SUDANI");
		JobOwner.put(2511,"LAVANYA SHENDRE");
		JobOwner.put(2154,"LAVANYA SUDANI");
		JobOwner.put(1753,"LAXMAN BHADSALE");
		JobOwner.put(114,"LAXMI NARAYANA PULI");
		JobOwner.put(383,"LEELA LOKESHWARI");
		JobOwner.put(2392,"LEON RICHARD DSOUZA");
		JobOwner.put(2345,"LOHITHA VINAYAKAMOORTHY");
		JobOwner.put(2020,"LOKESH MANOHAR BADGUJAR");
		JobOwner.put(1000,"M R VEENA");
		JobOwner.put(2206,"M S PRAVEEN");
		JobOwner.put(1241,"MADHAV CHEPURU");
		JobOwner.put(1712,"MADHAV GAVINI");
		JobOwner.put(401,"MADHU CHINMAY");
		JobOwner.put(1821,"MADHUMEETA SUNILKUMAR WARANKAR");
		JobOwner.put(2236,"MADHURI VIJAY BHANGRE");
		JobOwner.put(1758,"MAHEEDHAR TENALI");
		JobOwner.put(1438,"MAHENDAR NADIKUDA");
		JobOwner.put(528,"MAHENDER GOUD KOTHAPETA");
		JobOwner.put(1714,"MAHENDRA SADASHIV GAVHANE");
		JobOwner.put(1772,"MAHESH ASHOK VARKHEDE");
		JobOwner.put(306,"MAHESH GOUD ERAPURAM");
		JobOwner.put(1675,"MAHESH PABBU");
		JobOwner.put(2463,"Mahesh Sabale");
		JobOwner.put(1827,"MAHESH SHASHIKANT BHOSALE");
		JobOwner.put(1202,"MAHESHWARI B.");
		JobOwner.put(2350,"MAMATHA DIVYA KRUPA CHAPALA");
		JobOwner.put(2125,"Mamta Mistry");
		JobOwner.put(231,"MANASA ANNEBOINA");
		JobOwner.put(2152,"MANASA DADI");
		JobOwner.put(2535,"MANASA DUKANAM");
		JobOwner.put(2494,"Manasi Damle");
		JobOwner.put(2271,"MANDEEP KAUR DUA");
		JobOwner.put(1750,"MANGESH LAXMAN TARALKAR");
		JobOwner.put(2518,"MANI KUMAR REDDY GUNUKULA");
		JobOwner.put(2559,"MANISH KUMAR");
		JobOwner.put(2530,"MANISH REDDY SHIVAGARI");
		JobOwner.put(2375,"MANISHKUMAR ASHARAM PATEL");
		JobOwner.put(2367,"MANJUNATH MALAKAPPA UDACHAN");
		JobOwner.put(1598,"MANOHAR VENKATA VULLI");
		JobOwner.put(1561,"MANORATH SRISHTI MISHRA");
		JobOwner.put(2521,"MANOVIHAR RAIPUDI");
		JobOwner.put(2360,"MANSA RAMYA");
		JobOwner.put(964,"MANU MEHTA");
		JobOwner.put(1465,"MANVENDRA PRATAP MALL");
		JobOwner.put(2166,"MASOOMA FATIMA");
		JobOwner.put(1428,"MATHIN PASHA SHEK");
		JobOwner.put(1784,"MAYA NAIR");
		JobOwner.put(2529,"MAYANK UPRETI");
		JobOwner.put(1375,"MAYUR SINH BHUPENDRA SINH SOLANKI");
		JobOwner.put(1786,"MAYURESH MADHUKAR BHIDE");
		JobOwner.put(2500,"Mayuri Jayantrao Kulkarni");
		JobOwner.put(1664,"MD SHABUDDIN");
		JobOwner.put(422,"MD. RAZIUDDIN");
		JobOwner.put(352,"MD. SARFARAZ ALI");
		JobOwner.put(699,"MD.MANSOOR ALI KHAN");
		JobOwner.put(2428,"MEENA DWIVEDI");
		JobOwner.put(347,"MEENA KUMARI V.");
		JobOwner.put(2061,"MEHAJABIN MAHAMMADSHARIF SANADE");
		JobOwner.put(2526,"Mehul Sunil Waykar");
		JobOwner.put(1724,"MILIND RAVINDRA BHOPATKAR");
		JobOwner.put(2056,"MILIND SUDHAKAR KADAM");
		JobOwner.put(2245,"MINU S NAIR");
		JobOwner.put(349,"MISKEEN AHMED MD");
		JobOwner.put(1577,"MITHUN SATISH SHETYE");
		JobOwner.put(2238,"MITHUN SUBASH TATE");
		JobOwner.put(1011,"MOHAMMAD MASIULLAH");
		JobOwner.put(404,"MOHAMMED ADNAN");
		JobOwner.put(2527,"MOHAMMED IMRAN KHAN");
		JobOwner.put(685,"MOHAMMED NADEEM");
		JobOwner.put(1703,"MOHAMMED NISSAR");
		JobOwner.put(1795,"MOHAMMED SHABBIR KOTHAMBAWALA");
		JobOwner.put(2433,"MOHANA RAVITEJA GUTTA");
		JobOwner.put(410,"MOHD. NAYEEMUDDIN");
		JobOwner.put(425,"MOHD. SHIRAZ ALI ANSARI");
		JobOwner.put(2507,"MONICA AMBADAS WANKHEDE");
		JobOwner.put(971,"MONICA TIWARI");
		JobOwner.put(2419,"MOUNIKA GAIKAWAD");
		JobOwner.put(1994,"MOUNIKA TEMKER");
		JobOwner.put(2280,"MOUNIKA VELDANDI");
		JobOwner.put(620,"MOUNISH BARUA");
		JobOwner.put(2220,"MUBEEN GAFFAR MUNSHI");
		JobOwner.put(1732,"MUJAHID AQUEEL");
		JobOwner.put(1065,"MUKESH KUMAR MAURYA");
		JobOwner.put(2556,"Mukesh Prakash Rane");
		JobOwner.put(406,"MUKUL RANJAN");
		JobOwner.put(2200,"MURALI KRISHNA VELANKAYALA");
		JobOwner.put(119,"MURALIDHAR CHANDRAGIRI");
		JobOwner.put(1555,"MUSTAFA KAMAL");
		JobOwner.put(1624,"MUTHUKUMARAN M");
		JobOwner.put(1746,"MUZAFFAR KHAN");
		JobOwner.put(1362,"N DRAMAN NAUGBOUT NINA EUGENIE");
		JobOwner.put(780,"N JITHENDAR REDDY");
		JobOwner.put(2536,"NAGA AKHILA VENKATA SHALAKA");
		JobOwner.put(103,"NAGA BABU ARATIKATLA");
		JobOwner.put(2541,"NAGA SURYA SRIRAMYA GORTHI");
		JobOwner.put(97,"NAGALINGESWAR VUNGARALA");
		JobOwner.put(1,"NAGARAJ KRANTHI");
		JobOwner.put(2332,"NAKUL SHARMA");
		JobOwner.put(2039,"Nalini Chava");
		JobOwner.put(1985,"NALLAGONDA VISHAL");
		JobOwner.put(2315,"NAMRATA DNYANDEO SATONE");
		JobOwner.put(2431,"NAMRATA PRADEEP WAGH");
		JobOwner.put(1767,"NAMRATA SHAMSUNDAR MAHAMUNI");
		JobOwner.put(2225,"NANCY STANLEY PETER");
		JobOwner.put(2421,"NANDA JYOTHI CHANDESURE");
		JobOwner.put(509,"NARASIMHA RAO SAMBARAJU");
		JobOwner.put(1512,"NARASIMHULU PATHI");
		JobOwner.put(2403,"NARENDER SINGH NEGI");
		JobOwner.put(2013,"NARESH BABU KAGUPATI");
		JobOwner.put(2388,"NARESH DIGAMARTHI");
		JobOwner.put(355,"NARESH KUMAR GINNARAM");
		JobOwner.put(861,"NARESH MAREM");
		JobOwner.put(847,"NARESH SUNDER PAGEWALE");
		JobOwner.put(1449,"NASEER MOHAMMED");
		JobOwner.put(1432,"NASREEN PARVEEN SHAIK");
		JobOwner.put(287,"NATARAJAN BALA");
		JobOwner.put(357,"NAVATH KUMAR KODUMURI");
		JobOwner.put(2411,"NAVEEN KACHAM");
		JobOwner.put(514,"NAVEEN KUMAR KAMMAKOL");
		JobOwner.put(1464,"NAVEEN KUMAR SHARMA");
		JobOwner.put(2386,"NAVEENRAJ KESAVAMANI");
		JobOwner.put(2562,"NAVNEET KAUR");
		JobOwner.put(2512,"NAVYA SRI THADISHETTY");
		JobOwner.put(2323,"NAYAN KUMAR");
		JobOwner.put(1793,"NAYAN V DHAMORE");
		JobOwner.put(2473,"NAYANA APURVA SAMANT");
		JobOwner.put(1731,"NAZIRI ADIL");
		JobOwner.put(2130,"Neelam Bharti");
		JobOwner.put(1597,"NEERAJA PALAMAKULA");
		JobOwner.put(1682,"NEETI SHRIWASTAW");
		JobOwner.put(2422,"NEHA D PAWAR");
		JobOwner.put(1845,"NEHA MANOHAR BHOPALE");
		JobOwner.put(1485,"NEHA MITTAL");
		JobOwner.put(2308,"NEHA SUNIL MORE");
		JobOwner.put(997,"NIDHI MUNDADA");
		JobOwner.put(2272,"NIDHI PARESH MASRANI");
		JobOwner.put(2443,"NIKHIL ARUNKUMAR BHURE");
		JobOwner.put(1469,"NIKHIL GARGEYA NABURSE");
		JobOwner.put(1741,"NIKHIL PRADEEP APTE");
		JobOwner.put(2417,"NIKHILA RAYAPOLU");
		JobOwner.put(2347,"NILAM DHANRAJ KALBANDE");
		JobOwner.put(1702,"NINAD BHAGWAN MALADKAR");
		JobOwner.put(1164,"NIRMALYA GHATAK");
		JobOwner.put(7,"NIRUPAMA B.");
		JobOwner.put(2408,"NISHA SHANKAR DARWATKAR");
		JobOwner.put(1386,"NISHANT GUPTA");
		JobOwner.put(1615,"NITESH SHRIMANT JADHAV");
		JobOwner.put(1134,"NITHYA KADE");
		JobOwner.put(1822,"NUTAN RAMESH DESHMUKH");
		JobOwner.put(1474,"PADMA SUBRAMANI");
		JobOwner.put(2216,"PALLAVI SANTOSH KUDALE");
		JobOwner.put(2508,"PALLI LAHARI REDDY");
		JobOwner.put(2499,"Pankaj Chhagan Ghodeswar");
		JobOwner.put(1965,"PANKAJ DNYANESHWAR SARODE");
		JobOwner.put(1968,"PANKAJ KUMAR SINHA");
		JobOwner.put(1333,"PANKAJ MATHUR");
		JobOwner.put(1358,"PANKAJ POUL");
		JobOwner.put(1310,"PARANKUSH RAO CHEPURU");
		JobOwner.put(2169,"PARITOSH DESHMUKH");
		JobOwner.put(2374,"PAWAN KUMAR PANDEY");
		JobOwner.put(1834,"Phanindar B V R Motamarri");
		JobOwner.put(1378,"PHILOMENA J DHABADE");
		JobOwner.put(2226,"PHILOMENA RAJAN");
		JobOwner.put(1639,"PINALKUMAR DINESHBHAI PADALIYA");
		JobOwner.put(2471,"Piyush Kumar Chanchal");
		JobOwner.put(2012,"POOJA KRISHNAPRATAP CHAUHAN");
		JobOwner.put(1904,"POONAM RATAN PATIL");
		JobOwner.put(2474,"PRABHAKAR KAMAVARAMU");
		JobOwner.put(156,"PRABHAKARA MURTHY D.");
		JobOwner.put(523,"PRABHU NAGESH GOUD");
		JobOwner.put(1643,"PRADEEP KUMAR");
		JobOwner.put(1243,"PRADEEP KUMAR KUJUR");
		JobOwner.put(2321,"PRADEEP KUMAR PALLAPOTHU");
		JobOwner.put(163,"PRADIPTA MITRA");
		JobOwner.put(2390,"PRAFUL BHARTHARE");
		JobOwner.put(22,"PRAFUL H. MANGULLEY");
		JobOwner.put(152,"PRAFULLA SWAIN");
		JobOwner.put(2311,"PRAGATI VILAS ROKADE");
		JobOwner.put(2549,"Prakhar Vats");
		JobOwner.put(268,"PRAMOD KUMAR NAKKA");
		JobOwner.put(2163,"PRANAV TEJ");
		JobOwner.put(1689,"PRANAY KUMAR CHENNOJU");
		JobOwner.put(146,"PRASAD KULASEKARA");
		JobOwner.put(1727,"PRASAD SADASHIV SHIROLE");
		JobOwner.put(516,"PRASAD VEERABOTLU T. S. R.");
		JobOwner.put(1507,"PRASANNA LAKSHMI CHINTA");
		JobOwner.put(1250,"PRASANTHI LAKSHMI KOPPARAPU");
		JobOwner.put(2440,"PRASHANT KISHOR JADHAV");
		JobOwner.put(1903,"PRASHANT MACCHINDRA GOSAVI");
		JobOwner.put(1665,"PRASHANTHI NAGULA");
		JobOwner.put(627,"PRASON SUTHARI");
		JobOwner.put(2294,"PRASUN PATEL");
		JobOwner.put(2528,"PRATEEK CHAUDHARY");
		JobOwner.put(1510,"PRATHUYUSHA NARANAGARI");
		JobOwner.put(2456,"PRATIK DNYANESHWAR BEDARKAR");
		JobOwner.put(2317,"PRATIK KUMAR SHARMA");
		JobOwner.put(2402,"Pratik Sawant");
		JobOwner.put(2348,"PRATIMA MAHANANDA");
		JobOwner.put(2552,"Pratusha Kishor Patil");
		JobOwner.put(414,"PRATYUSH P");
		JobOwner.put(2460,"PRAVALLIKA REDDY PALAKALA");
		JobOwner.put(2266,"PRAVEEN GORTHI");
		JobOwner.put(104,"PRAVEEN GOUD MODEM");
		JobOwner.put(1673,"PRAVEEN KUMAR K");
		JobOwner.put(2458,"PRAVEEN KUMAR SATHBHAI");
		JobOwner.put(367,"PRAVEEN KUMAR SUDARSANAM");
		JobOwner.put(27,"PRAVEEN SAMAYAM");
		JobOwner.put(2322,"PRAVEEN TYAGI");
		JobOwner.put(304,"PRAVEEN VENKATA CHADARASIPALLI");
		JobOwner.put(219,"PRAVEENA CHALLA");
		JobOwner.put(1781,"PRAVIN ARUN PATIL");
		JobOwner.put(2468,"Pravin Deshmukh");
		JobOwner.put(2338,"PRAVIN NARSING BIRAJDAR");
		JobOwner.put(168,"PREETHA NAIR T. P.");
		JobOwner.put(2407,"PREETI SHUBHASHISH DAS");
		JobOwner.put(1111,"PRIYABRATA GUPTA");
		JobOwner.put(2389,"PRIYADARSHINE MAHAPATRA");
		JobOwner.put(1976,"PRIYANKA ARETI");
		JobOwner.put(1670,"PRIYANKA ESTHER SANTOSH PALAPARTHI");
		JobOwner.put(2053,"PRIYANKA GULAB GOSAVI");
		JobOwner.put(1690,"PRIYANKA GURUVUGARI");
		JobOwner.put(2352,"PRIYANKA KASTURI");
		JobOwner.put(2420,"PRIYANKA POTHULA");
		JobOwner.put(2555,"Priyanka Pradeep Jaiswal");
		JobOwner.put(2264,"PRIYANKA VUYYURU");
		JobOwner.put(2204,"PRIYARANJAN SAHU");
		JobOwner.put(2164,"PRUDHVI RAJ S");
		JobOwner.put(1347,"PUJITHA ATLURI");
		JobOwner.put(1992,"PULIAYNA AKSHITA");
		JobOwner.put(1998,"PULLA HIRANMAI");
		JobOwner.put(2221,"PURABSING PAWAR");
		JobOwner.put(1053,"R K VIKRAM SINGH");
		JobOwner.put(58,"RADHA");
		JobOwner.put(99,"RADHE SYAM BHAMIDIPATI");
		JobOwner.put(1977,"RAGHAVENDER REDDY SALKUTI");
		JobOwner.put(415,"RAGHAVENDRA KUMAR GAMPALA V.");
		JobOwner.put(130,"RAGHAVENDRA RAO KANAMARLAPUDI N. V. H.");
		JobOwner.put(1778,"RAGHAVENDRA YALLARADDI GIRADDI");
		JobOwner.put(902,"RAGHUNATH PASUPULETI");
		JobOwner.put(2376,"RAGUL SRINIVAS SRINIVASAN");
		JobOwner.put(2501,"Raheel Liyakat Deshmukh");
		JobOwner.put(1826,"RAHUL GARG");
		JobOwner.put(1684,"RAHUL KUMAR GAJANGI");
		JobOwner.put(1339,"RAHUL SURESH NEELAKANTAN");
		JobOwner.put(2331,"RAHUL TEJA VASPARI");
		JobOwner.put(2230,"RAJAN KUMAR CHOUDHARY");
		JobOwner.put(13,"RAJANI PASULA");
		JobOwner.put(1107,"RAJARSHI KUMAR DAS");
		JobOwner.put(416,"RAJENDER REDDY PATI");
		JobOwner.put(1718,"RAJENDRA DILIP SHINDE");
		JobOwner.put(1736,"RAJESH JOSE");
		JobOwner.put(2358,"RAJESH KARUNAKARAN");
		JobOwner.put(721,"RAJESH PINNAMANENI");
		JobOwner.put(1120,"RAJESHWAR MAKU");
		JobOwner.put(2064,"Rajeshwar Reddy Aenugu");
		JobOwner.put(1419,"RAJESHWARI PATEL SANARIA");
		JobOwner.put(2430,"RAJESWARA RAO DAMARLA");
		JobOwner.put(2387,"RAJNI KANT DHAR DUBEY");
		JobOwner.put(1549,"RAKESH DEPURU");
		JobOwner.put(1964,"RAKESH GALI");
		JobOwner.put(2520,"RAMA KRISHNAM RAJU DHANDU");
		JobOwner.put(1082,"RAMABADRA SATKULA");
		JobOwner.put(295,"RAMACHANDAR RAO J.");
		JobOwner.put(1647,"RAMADEVI KARNATI");
		JobOwner.put(1175,"RAMAKANTH PANUGANTI");
		JobOwner.put(2409,"Ramanathan Mahalingam");
		JobOwner.put(2068,"RAMANJANEYULU VENKATASATYASURYA VEMPRALA");
		JobOwner.put(1268,"RAMANJI REDDY UDUMULA");
		JobOwner.put(418,"RAMBABU CH.");
		JobOwner.put(1966,"RAMESH AYI");
		JobOwner.put(391,"RAMESH KAMMILI");
		JobOwner.put(1768,"RAMESH MAHADEV NAVALE");
		JobOwner.put(289,"RAMESH NAIDU K.");
		JobOwner.put(2488,"RAMESH PALLERLA");
		JobOwner.put(327,"RAMU SALAKA");
		JobOwner.put(1441,"RAMYA UMA CHINTAPENTA");
		JobOwner.put(2480,"RAMYA YADAV SANKATI");
		JobOwner.put(2017,"RASHID HUSSAIN MEHKRI");
		JobOwner.put(2357,"RASHMI ANIL BHANDARKAR");
		JobOwner.put(2237,"RASHMI AVINASH PANSARE");
		JobOwner.put(2248,"RASHMI DHANANJAY POTDAR");
		JobOwner.put(1847,"RASIKA RAMESH PAWAR");
		JobOwner.put(2301,"RASMITA CHOUDHURY");
		JobOwner.put(2128,"Ravalika Vadduri");
		JobOwner.put(2289,"RAVI KAMMARA");
		JobOwner.put(263,"RAVI KIRAN B.");
		JobOwner.put(2142,"RAVI KIRAN RAO POCHAMPALLY");
		JobOwner.put(1266,"RAVI KUMAR BAKKA");
		JobOwner.put(127,"RAVI KUMAR PULIPAKA");
		JobOwner.put(1486,"RAVI SHANKAR BHASKAR");
		JobOwner.put(1663,"RAVI SHANKAR GUPTA");
		JobOwner.put(1460,"RAVI TEJA VENKATA AKULA");
		JobOwner.put(1603,"RAVINDRA KUMAR DANDALA");
		JobOwner.put(2297,"REETHIKA NILETAM");
		JobOwner.put(1073,"REKHA NARENDRA");
		JobOwner.put(2435,"REKHA YADAV");
		JobOwner.put(243,"RENSON VARGHESE");
		JobOwner.put(2424,"RENU DATTATRAYA WANKHADE");
		JobOwner.put(2135,"Reyyi Shankar");
		JobOwner.put(1292,"RIMA BISWAS");
		JobOwner.put(2047,"Rita Khatei");
		JobOwner.put(1669,"RITIKA SENGUPTA");
		JobOwner.put(2444,"ROHAN PRASAD KHOLE");
		JobOwner.put(2305,"ROHAN RAVINDRA UNDALE");
		JobOwner.put(2176,"ROHIT VERMA");
		JobOwner.put(2362,"RUBY ASSIS ALMEIDA");
		JobOwner.put(2260,"RUBY VASHIST");
		JobOwner.put(2540,"RUKHSAR SHADMANI");
		JobOwner.put(2538,"RUPA PRABHUKUMAR CHAUHAN");
		JobOwner.put(2396,"Rupesh Kambli");
		JobOwner.put(2303,"RUPESH SUNIL PATIL");
		JobOwner.put(2239,"RUSHIKESH PANDURANG KAWADE");
		JobOwner.put(1196,"S ALEKHYA");
		JobOwner.put(2366,"SABIHA NAAZ BAIG");
		JobOwner.put(2371,"SACHIN APPA PAWAR");
		JobOwner.put(2208,"SACHIN APPASAHEB MANGALWEDHE");
		JobOwner.put(2496,"Sachin B. Madage");
		JobOwner.put(2267,"SACHIN BALASAHEB BORASE");
		JobOwner.put(2123,"Sachin Gulati");
		JobOwner.put(2525,"Sachin Prakash Lakhe");
		JobOwner.put(2438,"SACHIN RAMPRAKASH VIDHATE");
		JobOwner.put(2553,"Sagar Babarao Rathod");
		JobOwner.put(2126,"Sagar Thota");
		JobOwner.put(1166,"SAHAS KUMAR KANCHARLA");
		JobOwner.put(1658,"SAI ARUN BANDHAKAVI");
		JobOwner.put(2413,"SAI DEEPESH APPANA");
		JobOwner.put(2052,"Sai Kiran K");
		JobOwner.put(1511,"SAI KIRAN NYAMALA");
		JobOwner.put(1070,"SAI KRISHNA KISHORE");
		JobOwner.put(1499,"SAI KRISHNA PIRATLA");
		JobOwner.put(1407,"SAI KUMORR BANDARPALLY");
		JobOwner.put(2515,"SAI PRABHA AETTALLI");
		JobOwner.put(887,"SAI SAMAYAMANTRI");
		JobOwner.put(1632,"SAI SHANKAR PEDASINGU");
		JobOwner.put(2288,"SAI SREEJA JOSHI");
		JobOwner.put(2442,"SAIKIRAN KELOTH BAPIDI");
		JobOwner.put(745,"SAIKIRAN RANGARAJU");
		JobOwner.put(2091,"Saikumar Goud Gaddam");
		JobOwner.put(2398,"Saiprasad Gavandi");
		JobOwner.put(1058,"SAJID MOHAMMAD");
		JobOwner.put(47,"SAJU MALIACKAL");
		JobOwner.put(2379,"SALMANALI MOMIN");
		JobOwner.put(1608,"SAMADHAN SURESH SAMUDRA");
		JobOwner.put(2171,"SAMEER KUMAR VERMA");
		JobOwner.put(1706,"SAMEER SATHE");
		JobOwner.put(2319,"SAMIR CHANDRAKANT THETE");
		JobOwner.put(2560,"Sanal Chaudhary");
		JobOwner.put(635,"SANDEEP DANTU");
		JobOwner.put(1905,"SANDEEP DILIP NAWALE");
		JobOwner.put(2439,"SANDEEP SHAHAJI PAWAR");
		JobOwner.put(154,"SANDEEP SINGH");
		JobOwner.put(2543,"SANDHYA ALEX VULLAMPARTHI");
		JobOwner.put(2002,"SANDHYA KYASARAM");
		JobOwner.put(1754,"SANDIP ANANDRAO NALAWADE");
		JobOwner.put(2455,"SANISH MALAYIL RAMAN");
		JobOwner.put(1685,"SANJANA REDDY BORRA");
		JobOwner.put(1654,"SANJAY KUMAR KANTEGARI");
		JobOwner.put(1739,"SANJEEV JHA");
		JobOwner.put(2044,"Sanjeev Kumar Gosain");
		JobOwner.put(1841,"SANKET SAHEBRAO GIRAMKAR");
		JobOwner.put(1787,"SANOOP GOPI KUNNOTH");
		JobOwner.put(292,"SANTHOSH CHARY M.");
		JobOwner.put(2070,"SANTHOSH KUMAR ANANTHULA");
		JobOwner.put(1668,"SANTHOSH VALLALA");
		JobOwner.put(1299,"SANTOSH KUMAR KOLANPAKA");
		JobOwner.put(1638,"SANTOSH KUMAR NARLA");
		JobOwner.put(2247,"SANTOSH KUMAR SINGH");
		JobOwner.put(809,"SANTOSH KUMARI");
		JobOwner.put(1324,"SANTOSHI KUMARI GAJULA");
		JobOwner.put(2493,"SAPNA SHOBHIT LOHKARE");
		JobOwner.put(995,"SARAH ARCHANA AMBATI");
		JobOwner.put(135,"SARATH REDDY");
		JobOwner.put(584,"SARVANI PALADUGU");
		JobOwner.put(1513,"SARVESH KUMAR SINGH");
		JobOwner.put(1686,"SASHIDHAR JAKKALA");
		JobOwner.put(323,"SASTRY P. V. N.");
		JobOwner.put(1265,"SATHESH KUMAR");
		JobOwner.put(1176,"SATHISH KUMAR");
		JobOwner.put(2275,"SATHISH KUMAR ALLAM");
		JobOwner.put(96,"SATHYANARAYANA RAO K.");
		JobOwner.put(2405,"SATI SHANKAR");
		JobOwner.put(2004,"SATISH KUMAR BANGARU");
		JobOwner.put(915,"SATISH KUMAR M.");
		JobOwner.put(2101,"SATISH KUMAR NALLA");
		JobOwner.put(2210,"SATVINDER SINGH");
		JobOwner.put(527,"SATYANARAYANA BODDU");
		JobOwner.put(1709,"SATYANARAYANA PANCHALA");
		JobOwner.put(2300,"SATYANARAYANA POLA");
		JobOwner.put(2412,"SAUMYA RANJAN MISHRA");
		JobOwner.put(2252,"SAURABH SAYAJIRAO RENDALE");
		JobOwner.put(1751,"SAVINKUMAR VIJAYKUMAR P V");
		JobOwner.put(1079,"SAVITHA NAMDHARI");
		JobOwner.put(2470,"Sebastian Fernando");
		JobOwner.put(1730,"SEEMA SURESH SALVE");
		JobOwner.put(2316,"SEJAL VIPUL PAREKH");
		JobOwner.put(1456,"SHAHBAZ RASOOL");
		JobOwner.put(2427,"SHAHID SHAIKH");
		JobOwner.put(2365,"SHAHIN SHOUKATKHAN MOKASHI");
		JobOwner.put(1228,"SHAIK AEJAZ MOINUDDIN");
		JobOwner.put(1972,"SHAIK HASHMI SAFFINA");
		JobOwner.put(1463,"SHAILENDRA BISHT");
		JobOwner.put(1710,"SHAILESH DEOKAR");
		JobOwner.put(1707,"SHAJI PARAMESHWARAN");
		JobOwner.put(2509,"SHALINI KANAPARTHI");
		JobOwner.put(1458,"SHALINI KOTHAKONDA");
		JobOwner.put(111,"SHAMEEL SHARMA");
		JobOwner.put(1765,"SHANKAR MURLIDHAR ROLE");
		JobOwner.put(315,"SHANKAR RAO TALLURI");
		JobOwner.put(2466,"Shanki Walwatkar");
		JobOwner.put(1763,"SHARAD SHRIPATI PATIL");
		JobOwner.put(2459,"SHARON ROJA AKULA");
		JobOwner.put(2304,"SHASHIL PRAKASH POHANKAR");
		JobOwner.put(1777,"SHEETAL RAJENDRA CHAUDHARI");
		JobOwner.put(1535,"SHIKHAR SINGH");
		JobOwner.put(1969,"SHILPA BASHETTY");
		JobOwner.put(788,"SHILPA VIDUR");
		JobOwner.put(1410,"SHILPEE MANDEWALKER");
		JobOwner.put(2514,"SHINCY SAM");
		JobOwner.put(1728,"SHINOD PARAMBATH");
		JobOwner.put(2038,"Shishir Tripathi");
		JobOwner.put(1761,"SHITAL SURAJ KHARTAD");
		JobOwner.put(2479,"SHIVA KRISHNA PONUGANTI");
		JobOwner.put(2034,"Shiva Kumar Narlagiri");
		JobOwner.put(2469,"Shivendra Prajapati");
		JobOwner.put(2337,"SHIVESH KUMAR");
		JobOwner.put(2282,"SHOBHARANI POLASA");
		JobOwner.put(1422,"SHOBHIT KUMAR");
		JobOwner.put(1620,"SHOWKATH ALI SYED");
		JobOwner.put(2414,"SHRAVAN GATTU");
		JobOwner.put(2174,"SHRAVAN KUMAR KUDIKALA");
		JobOwner.put(2092,"Shravan Kumar Thumula");
		JobOwner.put(2341,"SHREYA KULKARNI");
		JobOwner.put(1766,"SHRIKANT BALISHA JADHAV");
		JobOwner.put(2213,"SHRIKANT NIVRUTTI NAGRE");
		JobOwner.put(2498,"Shrikant Pradeep Hazare");
		JobOwner.put(2395,"Shrikant Sunchu");
		JobOwner.put(2150,"SHRUTHI NUNNA");
		JobOwner.put(1990,"SHRUTHI SUNIL");
		JobOwner.put(1790,"SHUBHANGI SHIVAJI DAREKAR");
		JobOwner.put(1733,"SHWETA CHANDRAKANT PATIL");
		JobOwner.put(1771,"SHWETA RAGHUNATH SONAWANE");
		JobOwner.put(2281,"SIDDESH GALI");
		JobOwner.put(1963,"SIDDHARTH SRIVASTAVA");
		JobOwner.put(2484,"SINDHURA BOINAPALLY");
		JobOwner.put(1163,"SIREESHA NARAM");
		JobOwner.put(2349,"SIRI CHANDANA RAVOORI");
		JobOwner.put(2516,"SIRISHA NAGULAPALLI");
		JobOwner.put(1514,"SIRISHA VULUPU");
		JobOwner.put(2295,"SIROSH M");
		JobOwner.put(812,"SIVA DURGA YEDALA");
		JobOwner.put(849,"SIVA KRISHNA MUTHYALU");
		JobOwner.put(1578,"SIVA PRASAD MADHU SATYA VEERA VENKATA GOPASANA");
		JobOwner.put(1662,"SIVALAKSHMI GADIYARAM");
		JobOwner.put(2385,"SIVASAKTHI SUBRAMANIAM");
		JobOwner.put(2451,"SNEHA BOINA");
		JobOwner.put(2173,"SNEHA SATISH RAJMANE");
		JobOwner.put(2242,"SNEHA SHAILENDRA JHA");
		JobOwner.put(1035,"SNEHA SHANKAR CHAINANI");
		JobOwner.put(1398,"SNEHA SINGH");
		JobOwner.put(2445,"SNEHA SURESH SALVE");
		JobOwner.put(2306,"SNEHAL ASHOK RAUT");
		JobOwner.put(2063,"SNEHAL BABAJI MUSALE");
		JobOwner.put(1721,"SNEHAL DAYAMA");
		JobOwner.put(2155,"SNEHAL PRATAP YERAM");
		JobOwner.put(2196,"SNEHAL SURESH POTE");
		JobOwner.put(2475,"SNEHANKUR ADAK");
		JobOwner.put(1973,"SOLOMON KACHHAP");
		JobOwner.put(2162,"SOLOMON RAJ BURUKA");
		JobOwner.put(2467,"Somnath More");
		JobOwner.put(2186,"SONALI BIRADAR");
		JobOwner.put(2566,"Sonali Garg");
		JobOwner.put(1505,"SONANI PATRA");
		JobOwner.put(1193,"SOUJANYA ARRAM");
		JobOwner.put(1633,"SOUMEN CHATTERJEE");
		JobOwner.put(1970,"SOUNDARYA MANNE");
		JobOwner.put(2278,"SOUNDARYA N YADAV");
		JobOwner.put(2019,"SOURABH SAHU");
		JobOwner.put(1096,"SOWED KAMAL MUHAMMED");
		JobOwner.put(109,"SOWJANYA SATUKURI");
		JobOwner.put(2353,"SRAVANI GUNJAPALLE");
		JobOwner.put(2143,"SRAVANI JONNALAGADDA");
		JobOwner.put(280,"SREE GANESH GUNTY V. N.");
		JobOwner.put(778,"SREEDHAR KALVA");
		JobOwner.put(1552,"SREEDHAR YADAV NALI");
		JobOwner.put(25,"SREEJITH MK");
		JobOwner.put(2175,"SREEKANT BISWAL");
		JobOwner.put(1749,"SREELESH NARAYAN KURUP");
		JobOwner.put(277,"SREENIVAS GUNTURU S.");
		JobOwner.put(427,"SREENIVASULU JAKKA");
		JobOwner.put(2513,"SREEVANI YERUVA");
		JobOwner.put(1604,"SRI CHARAN POOSARLA");
		JobOwner.put(2450,"SRI LAKSHMI SWARNA DUPAGUNTLA");
		JobOwner.put(2452,"SRI RAM VENKATESH");
		JobOwner.put(74,"SRIDHAR BODIRE");
		JobOwner.put(1430,"SRIDHAR BOGA");
		JobOwner.put(372,"SRIGANGA KASTURI");
		JobOwner.put(2285,"SRIJA REDDY RAVA");
		JobOwner.put(2334,"SRIKANTH BOYINA");
		JobOwner.put(88,"SRIKANTH GUDAPATI");
		JobOwner.put(1203,"SRIKANTH REDDY PAMULAPATI");
		JobOwner.put(68,"SRIKANTH SALANDRI");
		JobOwner.put(2542,"SRILEKHA MANI");
		JobOwner.put(1180,"SRINIVAS CH.");
		JobOwner.put(1636,"SRINIVAS PALLERLA");
		JobOwner.put(2098,"SRINIVAS POTDAR");
		JobOwner.put(1630,"SRINIVAS POTTACHERUVA");
		JobOwner.put(1008,"SRINIVAS SALLURI");
		JobOwner.put(1667,"SRINIVASA RAO KESANI");
		JobOwner.put(1962,"SRINUBABU RAVILLA");
		JobOwner.put(1420,"SRIRAM SIVAKUMAR");
		JobOwner.put(2274,"SRISHTI PANDEY");
		JobOwner.put(2510,"SRUTHI PRASAD CHILAKAMARRY");
		JobOwner.put(2279,"SRUTHI SENAPATHI");
		JobOwner.put(2448,"Steffi");
		JobOwner.put(1775,"SUCHISMITA KANUNGO");
		JobOwner.put(2310,"SUCHITA PRABHAKAR BHALERAO");
		JobOwner.put(1182,"SUDARSHAN PANDIKONDA");
		JobOwner.put(26,"SUDHARSHAN MEKALA");
		JobOwner.put(688,"SUDHEER KUMAR");
		JobOwner.put(1961,"SUDHIR KUMAR RACHAKONDA");
		JobOwner.put(2217,"SUDHIR SOUDAGAR KUMBHAR");
		JobOwner.put(1332,"SUHASINI GULLA");
		JobOwner.put(702,"SUJANA N.");
		JobOwner.put(2286,"SUJANA SRI MADDELA");
		JobOwner.put(1404,"SUJATA DAS");
		JobOwner.put(1162,"SUJATHA PARASA");
		JobOwner.put(1743,"SUJEET SANDIPANRAO FARTADE");
		JobOwner.put(1634,"SUKI SUBRAMANIAM GANAPATHY SUNDARAM");
		JobOwner.put(2122,"Sulabh Mathur");
		JobOwner.put(2570,"SUMAN KUMAR SINGH");
		JobOwner.put(1625,"SUMEDH SURESH BANSOD");
		JobOwner.put(2258,"SUMIT KUMAR NAYAK");
		JobOwner.put(2265,"SUMMY MISHRA");
		JobOwner.put(1554,"SUNIL DUBBA");
		JobOwner.put(100,"SUNIL KUMAR B.");
		JobOwner.put(2148,"SUNITHA GIDDALA");
		JobOwner.put(2531,"SURAJ KUMAR GUBBA");
		JobOwner.put(1799,"SURAJ MUKTAJI MUNJGUDE");
		JobOwner.put(647,"SURENDER MINIPURI");
		JobOwner.put(1979,"SURENDRA G S NARAYANBATLA");
		JobOwner.put(2096,"Surendra Kumar Kottu");
		JobOwner.put(1725,"SURESH BABU KALVA");
		JobOwner.put(14,"SURESH BABU KANDUKURI");
		JobOwner.put(296,"SURESH G. PANDHARPURKAR");
		JobOwner.put(1424,"SURESH KUMAR PARASURAMAN");
		JobOwner.put(1401,"SURESH MIDDE");
		JobOwner.put(1726,"SURESH PINDI");
		JobOwner.put(196,"SURESH VARMA MANTENA");
		JobOwner.put(2569,"SUSAN BATTULA");
		JobOwner.put(2111,"Sushant Shekar Jha");
		JobOwner.put(2342,"SUSHMA BHUPATHIRAJU");
		JobOwner.put(2482,"SUSHMA V N");
		JobOwner.put(2534,"SUSHMITHA KANUKUNTLA");
		JobOwner.put(2485,"SUSHREE SANGITA JENA");
		JobOwner.put(2287,"SUSMITHA CHELIMEDA");
		JobOwner.put(2539,"SWAPNA SREE VEDANTAM");
		JobOwner.put(1807,"SWAPNIL BARAVKAR");
		JobOwner.put(1278,"SWAPNIL PHUKE");
		JobOwner.put(1742,"SWAPNIL SURESH JOSHI");
		JobOwner.put(1450,"SWAROOP UDAY RATAN JUJJAVARAPU");
		JobOwner.put(2568,"SWATHI ONTEDDU");
		JobOwner.put(2434,"SWATHI PRIYA JAKATI");
		JobOwner.put(2436,"SWATHI PRIYANKA DAKOJU");
		JobOwner.put(2364,"SWATI MAHADEV MAHADAK");
		JobOwner.put(829,"SWETHA EADAMA");
		JobOwner.put(1983,"SYED FAIZAN UL HASAN");
		JobOwner.put(2377,"SYED FAZAL");
		JobOwner.put(2095,"SYED ILYAZ");
		JobOwner.put(389,"SYED WAJEEHUDDIN HUSSAINI");
		JobOwner.put(1622,"SYLVIA SUNANDINI SEVANTH");
		JobOwner.put(2100,"TAMAL PAUL");
		JobOwner.put(1840,"TANAJI RAGHUNATH YETALE");
		JobOwner.put(2546,"Tanmayee Vinaykumar Nyayadhish");
		JobOwner.put(1839,"TANULATA HARISH WALAWALKAR");
		JobOwner.put(1342,"TANVI MADISHETTY");
		JobOwner.put(2454,"TARUN KUMAR SANKU");
		JobOwner.put(1776,"TEJASVEE RAJARAM CHIPLUNKAR");
		JobOwner.put(2453,"TEJASWINI VUPPALA");
		JobOwner.put(2277,"THANMAI KALIGE");
		JobOwner.put(2042,"Thejaswini Vemula");
		JobOwner.put(2296,"TIRUMALA SIVA KRISHNA PALADUGU");
		JobOwner.put(2222,"TOPNICK LOUIS THOMAS");
		JobOwner.put(2299,"TRUPTI ADITYA DESHMUKH");
		JobOwner.put(1770,"TRUPTI DEEPAK SASANE");
		JobOwner.put(831,"TULASI REDDY PAILLA");
		JobOwner.put(2223,"TUSHAR KARBHARI VANIKAR");
		JobOwner.put(824,"UMA MAHESH JAKKULA");
		JobOwner.put(804,"UMA RANI M");
		JobOwner.put(1382,"UMAR SHAREEF SHAIK");
		JobOwner.put(1755,"UMESH BHANUDAS BHOSALE");
		JobOwner.put(1611,"V.S.S.S.ANAND GOPAL");
		JobOwner.put(704,"V.UDAJA");
		JobOwner.put(2548,"Vaibhavi Nilkanth Kate");
		JobOwner.put(2250,"VALLABH VAIBHAV GUND");
		JobOwner.put(63,"VARDHAN");
		JobOwner.put(1729,"VARSHA MANKAR");
		JobOwner.put(660,"VARUN SINGH");
		JobOwner.put(1692,"VASU NANGULURI");
		JobOwner.put(262,"VASU REDDY MALLELA");
		JobOwner.put(2041,"Ved Prakash Shukla");
		JobOwner.put(724,"VEENA CHEPURI");
		JobOwner.put(2161,"VEENA KUMARI PALLE");
		JobOwner.put(1031,"VEERESH JOGU");
		JobOwner.put(2418,"VENI ALLEGALA");
		JobOwner.put(950,"VENKAT RAM REDDY PEDDITI");
		JobOwner.put(1567,"VENKATA KRANTHI KUMAR KOTTE");
		JobOwner.put(2481,"VENKATA MADHAVI BOGANI");
		JobOwner.put(2339,"VENKATA PRASANTH NUTHAKKI");
		JobOwner.put(265,"VENKATA RAJESH MEDISETTI");
		JobOwner.put(2335,"VENKATA SATISH VELUGUBANTLA");
		JobOwner.put(331,"VENKATESH JULURY");
		JobOwner.put(2293,"VENKATESH M");
		JobOwner.put(378,"VENKATESHAM KANNA");
		JobOwner.put(2476,"VENKATESWARA RAO NAMBURI");
		JobOwner.put(431,"VENUGOPAL SONI KINTADA");
		JobOwner.put(1455,"VENUGOPAL ULLAM");
		JobOwner.put(2563,"Vidya Khati");
		JobOwner.put(2069,"VIJAY KAUSHAL");
		JobOwner.put(241,"VIJAY KUMAR DONTHINENI");
		JobOwner.put(1829,"VIJAY KUMAR K KUTTY");
		JobOwner.put(1803,"VIJAY VISHNU BAGILKAR");
		JobOwner.put(2437,"VIJAY VITTHAL SATHE");
		JobOwner.put(2257,"VIJI KUSHWAHA");
		JobOwner.put(379,"VIKRAM PODAPATI");
		JobOwner.put(1323,"VIKRANTH VENKAT THORAM");
		JobOwner.put(2046,"Vimlesh Kumar");
		JobOwner.put(141,"VINAI SANKUNNI");
		JobOwner.put(1547,"VINAY KUMAR KUYYA");
		JobOwner.put(1032,"VINAY KUMAR MANDULA");
		JobOwner.put(1745,"VINAY RAKHAMAJI JADHAV");
		JobOwner.put(2049,"Vindhyachal Tiwari");
		JobOwner.put(2533,"VINITHA AMADABOINA");
		JobOwner.put(2490,"VINITHA MYNAM");
		JobOwner.put(2446,"VINOD DEVAIAH MANCHALA");
		JobOwner.put(218,"VINOD KUMAR GAJJALA");
		JobOwner.put(576,"VINOD KUMAR GEDDADA");
		JobOwner.put(1363,"VINOD KUMAR KAYATHI GANESH");
		JobOwner.put(2009,"VINYASA TIRUMALA SINGARAYAKONDA");
		JobOwner.put(2503,"Vishakha Ramesh Bhadake");
		JobOwner.put(2336,"VISHAL JOSHI");
		JobOwner.put(1072,"VISHALI CHOPPALA");
		JobOwner.put(2117,"Vishawjeet Anil Deshmukh");
		JobOwner.put(1426,"VISHNU MURTHY VOLLALLA");
		JobOwner.put(1524,"VISHNU PUJITHA ATLURI");
		JobOwner.put(2156,"VISHNUVARDHAN REDDY GAJJALA");
		JobOwner.put(2567,"Vishwajeet Raosaheb Kadam");
		JobOwner.put(1738,"VIVEK NAROTTAM GARG");
		JobOwner.put(2464,"Vivek Sable");
		JobOwner.put(2240,"VIVEK SHESHMALJI SHARMA");
		JobOwner.put(2393,"Vivek Shetty");
		JobOwner.put(1062,"VS NAGA BABU YALLA");
		JobOwner.put(2368,"WAJID ABDUL WAHID SHAIKH");
		JobOwner.put(758,"WASEEM AHMED");
		JobOwner.put(21,"YADAVALLI VIJAY");
		JobOwner.put(2465,"Yasar Ahmed");
		JobOwner.put(2557,"Yasar Sharif Dalal");
		JobOwner.put(2449,"YASMIN ZAHEER SHAIKH");
		JobOwner.put(1594,"YASWANTH KODALI");
		JobOwner.put(1744,"YOGESH BACHCHE");
		JobOwner.put(1252,"YOGITA DAGIA");
		JobOwner.put(1387,"ZAKIR HUSSAIN");
//=====================================================================================
		OfficeID.put(11,"AP DP");
		OfficeID.put(20,"AP IA");
		OfficeID.put(47,"APIA-EU");
		OfficeID.put(48,"APIA-US");
		OfficeID.put(71,"AV DP");
		OfficeID.put(72,"AV Scripting");
		OfficeID.put(13,"Belgium DP");
		OfficeID.put(29,"Charting");
		OfficeID.put(42,"Dimensions");
		OfficeID.put(53,"Dimensions Training - IOM");
		OfficeID.put(52,"Dimensions Training - TOM");
		OfficeID.put(92,"Dubai DP");
		OfficeID.put(91,"Dubai Scripting");
		OfficeID.put(12,"France DP");
		OfficeID.put(15,"France IA");
		OfficeID.put(40,"Germany DP");
		OfficeID.put(54,"Germany DP-FMDS");
		OfficeID.put(18,"Germany IA");
		OfficeID.put(27,"Global Intractive Dev.");
		OfficeID.put(69,"HCDP");
		OfficeID.put(70,"HCSC");
		OfficeID.put(64,"HR");
		OfficeID.put(51,"Iclick DP");
		OfficeID.put(96,"India Link Research Center");
		OfficeID.put(74,"IPM");
		OfficeID.put(73,"IT");
		OfficeID.put(43,"KM and Technology");
		OfficeID.put(76,"MB Automation support");
		OfficeID.put(67,"MB DP");
		OfficeID.put(68,"MB Scripting");
		OfficeID.put(80,"MBNA Data Processing");
		OfficeID.put(79,"MBNA Scripting");
		OfficeID.put(66,"MIS");
		OfficeID.put(62,"Mobile Research");
		OfficeID.put(63,"Mobile Research Center");
		OfficeID.put(41,"MS Group A");
		OfficeID.put(55,"MS Group B");
		OfficeID.put(26,"NIPO IA");
		OfficeID.put(44,"Non-Billable");
		OfficeID.put(45,"ORQC");
		OfficeID.put(46,"ORWP");
		OfficeID.put(8,"Other Europe DP");
		OfficeID.put(16,"Other Europe IA");
		OfficeID.put(56,"Other NA DP");
		OfficeID.put(57,"Other NA IA");
		OfficeID.put(77,"PQM");
		OfficeID.put(94,"Pune AV DP");
		OfficeID.put(93,"Pune AV Scripting");
		OfficeID.put(75,"Pune Coding");
		OfficeID.put(88,"Pune MB GM DP");
		OfficeID.put(87,"Pune MB GM Scripting");
		OfficeID.put(82,"Pune MB NA DP");
		OfficeID.put(81,"Pune MB NA Scripting");
		OfficeID.put(84,"Pune MB UK/EU DP");
		OfficeID.put(83,"Pune MB UK/EU Scripting");
		OfficeID.put(95,"Pune MB Unilever");
		OfficeID.put(90,"Pune QA DP");
		OfficeID.put(89,"Pune QA Scripting");
		OfficeID.put(98,"Pune TNS Dubai DP");
		OfficeID.put(78,"QCSC");
		OfficeID.put(28,"Reporting");
		OfficeID.put(97,"Research Operations Coordination");
		OfficeID.put(3,"Sorensen DP");
		OfficeID.put(49,"Spain DP");
		OfficeID.put(59,"SRIA (Smart Research Interactive)");
		OfficeID.put(30,"SS- Australia Coding");
		OfficeID.put(31,"SS- Canada Coding");
		OfficeID.put(38,"SS- France Coding");
		OfficeID.put(33,"SS- Japan Coding");
		OfficeID.put(34,"SS- Media Intelligence");
		OfficeID.put(35,"SS- Singapore Coding");
		OfficeID.put(36,"SS- UK Coding");
		OfficeID.put(37,"SS- US Coding");
		OfficeID.put(65,"T&amp;D");
		OfficeID.put(2,"TRIM Processing");
		OfficeID.put(58,"TSC");
		OfficeID.put(7,"UK DP");
		OfficeID.put(9,"UK DP Healthcare");
		OfficeID.put(25,"UK IA");
		OfficeID.put(23,"UK IA Healthcare");
		OfficeID.put(60,"UKQC");
		OfficeID.put(1,"US DP Group A");
		OfficeID.put(4,"US DP Group B");
		OfficeID.put(6,"US DP Group C");
		OfficeID.put(10,"US DP Healthcare");
		OfficeID.put(14,"US IA Group A");
		OfficeID.put(19,"US IA Group B");
		OfficeID.put(21,"US IA Group C");
		OfficeID.put(22,"US IA Healthcare");
		OfficeID.put(5,"US PG DP");
		OfficeID.put(17,"US PG IA");
		OfficeID.put(50,"USDP Dimensions");
//==============================================================================================			
		ProgressID.put(41,"Awaiting Client feedback");
		ProgressID.put(33,"Awaiting inputs/ data");
		ProgressID.put(42,"Awaiting QC feedback");
		ProgressID.put(37,"Awaiting QC/ client feedback");
		ProgressID.put(35,"Axes preparation in progress");
		ProgressID.put(2,"Cancelled/Lost");
		ProgressID.put(43,"Checking in progress");
		ProgressID.put(31,"Closed/ Completed");
		ProgressID.put(34,"Data cleaning in progress");
		ProgressID.put(32,"Not started yet/ Postponed");
		ProgressID.put(1,"Open");
		ProgressID.put(36,"Processing in progress");
		ProgressID.put(40,"Working on additional/ extra requests");
		ProgressID.put(38,"Working on business solutions/ Special analysis");
		ProgressID.put(39,"Working on data delivery (Quanvert, excel, etc.)");
//=================================================================================
		ExecID.put(1022,"Abby Kiani");
		ExecID.put(6218,"Abdelshahid, Amy");
		ExecID.put(2686,"Abidur Choudhury");
		ExecID.put(1607,"adam cruits");
		ExecID.put(3246,"Adam Lancaster");
		ExecID.put(3083,"Adam Pemberton");
		ExecID.put(4410,"Adil Hamid");
		ExecID.put(4534,"Adrian Rolling");
		ExecID.put(3788,"Aibek Iliasov");
		ExecID.put(4352,"Aileen Bradley");
		ExecID.put(5667,"Akram");
		ExecID.put(1138,"Alastair Graham");
		ExecID.put(4940,"Alberto Hernandez");
		ExecID.put(1513,"Alex Duckett");
		ExecID.put(1205,"Alex Rawlings");
		ExecID.put(2966,"Alex Rubner");
		ExecID.put(1914,"Alex Shepherd");
		ExecID.put(2114,"Alex Thornton");
		ExecID.put(4018,"Alexa Nightingale");
		ExecID.put(2537,"Alexander Kirycos");
		ExecID.put(6040,"Alexander Wong");
		ExecID.put(3280,"Alexia Anghelakou");
		ExecID.put(5922,"Alice Coram");
		ExecID.put(3352,"Alice Fearn");
		ExecID.put(3289,"Alice Fitzpatrick");
		ExecID.put(2967,"Aline Simon");
		ExecID.put(6755,"Allcock Carli");
		ExecID.put(2450,"amali dealwis");
		ExecID.put(3624,"Amie Kernan");
		ExecID.put(2721,"Amit Lakhani");
		ExecID.put(5134,"Amy Chilcott");
		ExecID.put(1484,"AMY SANGWAY");
		ExecID.put(5734,"Anastasia Smolina");
		ExecID.put(5158,"Andrea Juranova");
		ExecID.put(2191,"Andrea Kinver");
		ExecID.put(2792,"Andrea Virks");
		ExecID.put(2486,"Andrew Dodds");
		ExecID.put(1606,"andrew green");
		ExecID.put(2364,"Andrew Hutton");
		ExecID.put(2364,"Andrew Hutton");
		ExecID.put(2985,"Andy Brember");
		ExecID.put(4332,"Andy Bromley");
		ExecID.put(4213,"Angela Hoffman");
		ExecID.put(1422,"Angelica Lorenzo");
		ExecID.put(3668,"Anita Akers");
		ExecID.put(1004,"Anita Emery");
		ExecID.put(1395,"Ann Bellchambers");
		ExecID.put(1219,"Anna Dudek");
		ExecID.put(3445,"Anna Geffert");
		ExecID.put(1808,"Anna Kidd");
		ExecID.put(2736,"Anna Vasilyeva");
		ExecID.put(3521,"Anne Cheung");
		ExecID.put(1857,"Anne Coll");
		ExecID.put(2332,"Anne Collins");
		ExecID.put(4192,"Annick Millot");
		ExecID.put(1908,"April Kinnear");
		ExecID.put(5912,"Ashleigh.Whitehouse");
		ExecID.put(2518,"ASHOK SHARMA");
		ExecID.put(4880,"Asun Del Valle");
		ExecID.put(6279,"Atie Arian");
		ExecID.put(3215,"Ayelet Schulz");
		ExecID.put(6266,"Bains, Kavan");
		ExecID.put(5088,"Barney Guyatt");
		ExecID.put(4570,"Ben Mansell");
		ExecID.put(5895,"Benedict Kelly");
		ExecID.put(5283,"Berger Dasha");
		ExecID.put(1842,"BERNARD Claire");
		ExecID.put(5796,"Berrymen Ben");
		ExecID.put(1128,"Beth Williams");
		ExecID.put(2625,"Bob Burgoyne");
		ExecID.put(3153,"Bradut Avram");
		ExecID.put(2729,"Brian Stephenson");
		ExecID.put(1094,"Brigitta Horup");
		ExecID.put(5142,"Brown, Conor");
		ExecID.put(3203,"Camilla Huckle");
		ExecID.put(3369,"Camille Foujols");
		ExecID.put(3697,"CARLA STOCKS");
		ExecID.put(2953,"Carly Sharpe");
		ExecID.put(1098,"Carol Fraser");
		ExecID.put(3258,"Carole Lenox");
		ExecID.put(1625,"Caroline Arnold");
		ExecID.put(1344,"caroline.galaj.leflour");
		ExecID.put(1294,"Carolyn Dixon");
		ExecID.put(4512,"Carrie Harding");
		ExecID.put(4243,"Catherine Fowler");
		ExecID.put(1703,"Catriona West");
		ExecID.put(1353,"Charlotte Blythe");
		ExecID.put(1479,"Charlotte Clifford");
		ExecID.put(5285,"Chirstian Giles");
		ExecID.put(4879,"Chloe Petty");
		ExecID.put(5600,"Chris Beeby");
		ExecID.put(3149,"Chris Brown");
		ExecID.put(2062,"Chris Gravestock");
		ExecID.put(2394,"Chris Knibbs");
		ExecID.put(4923,"Christelle Muller");
		ExecID.put(5189,"Christie Amob");
		ExecID.put(2392,"Christina Beza");
		ExecID.put(6714,"Christopher Thresher Andrews");
		ExecID.put(4998,"Chubb, Katy");
		ExecID.put(5782,"Cichon Jerek");
		ExecID.put(4233,"Claire Bassett");
		ExecID.put(1945,"Claire Edwards");
		ExecID.put(2929,"Claire Jackson");
		ExecID.put(2929,"Claire Jackson");
		ExecID.put(1663,"Claire Tsang");
		ExecID.put(2074,"Clara Abad");
		ExecID.put(1296,"Clelia DiTacchio");
		ExecID.put(6002,"Clodagh.Roche-Kelly");
		ExecID.put(6419,"Coleman, Emma");
		ExecID.put(5321,"Colin Macleod");
		ExecID.put(2136,"DAILLIEZ Nathalie");
		ExecID.put(3962,"Dan Dexter");
		ExecID.put(4170,"Dan Jenkins");
		ExecID.put(945,"Daniel Curl");
		ExecID.put(4533,"Daniel Fox");
		ExecID.put(1757,"Daniel Kay");
		ExecID.put(1507,"Daniel Stockwell");
		ExecID.put(4434,"Danielle Todd");
		ExecID.put(3473,"Darren Henry");
		ExecID.put(5450,"Darshini Mahtha");
		ExecID.put(4844,"Darshita Govind");
		ExecID.put(4627,"David Crouch");
		ExecID.put(3553,"David Currie");
		ExecID.put(1718,"David Perry");
		ExecID.put(4766,"David Voss");
		ExecID.put(5520,"Dean Cope");
		ExecID.put(2562,"Deborah Fox");
		ExecID.put(4102,"Denise De Souza");
		ExecID.put(6188,"Diane Goff");
		ExecID.put(4357,"Divya Iyer");
		ExecID.put(4130,"Dmitry Isupov");
		ExecID.put(1896,"Douglas Dalziel");
		ExecID.put(5939,"Driscoll, Catherine");
		ExecID.put(2196,"Duncan Stewart");
		ExecID.put(5476,"Elaine Chen");
		ExecID.put(5733,"elBabili, Haiete");
		ExecID.put(3084,"Eleni Romanou");
		ExecID.put(1078,"Elisabeth Le Gall");
		ExecID.put(2837,"Elise Roche");
		ExecID.put(3487,"Elizabeth Le Gall");
		ExecID.put(4183,"Emese Peter");
		ExecID.put(1212,"Emily Davidson");
		ExecID.put(3170,"Emily Goddard");
		ExecID.put(1249,"Emma Dolby");
		ExecID.put(3356,"Emma Fencott");
		ExecID.put(5045,"Emma Johns");
		ExecID.put(4802,"Emma Mozley");
		ExecID.put(2251,"Erika Montoya");
		ExecID.put(2144,"Euan Mackay");
		ExecID.put(1810,"Eva Iglesias");
		ExecID.put(3159,"Evans, Michael");
		ExecID.put(2821,"FABIENNE CADENAT");
		ExecID.put(5819,"Fahilogullari Sinan");
		ExecID.put(1238,"Felix Chang");
		ExecID.put(5929,"Fiona Watt");
		ExecID.put(5671,"Fisher, Lucy");
		ExecID.put(4146,"Florian Rasp");
		ExecID.put(6423,"Foster, Janelle");
		ExecID.put(5036,"Frances Hamilton");
		ExecID.put(2104,"Francesca Antoniades");
		ExecID.put(5875,"Francesca Din");
		ExecID.put(1119,"Francis Bolton");
		ExecID.put(1614,"Frank Fonton");
		ExecID.put(3746,"Frank Wood");
		ExecID.put(3500,"Gail Sayer");
		ExecID.put(3257,"Gareth Bellamy");
		ExecID.put(1423,"Gareth Nash");
		ExecID.put(5063,"Gemma Cass");
		ExecID.put(1841,"Gemma Clissold");
		ExecID.put(2509,"Gina Lagos");
		ExecID.put(6484,"Godfroy Laurent");
		ExecID.put(1917,"Goran Jovetic");
		ExecID.put(2409,"Gosia Pietniewicz");
		ExecID.put(4778,"Grace Middlehurst");
		ExecID.put(3377,"Graeme Smith");
		ExecID.put(1171,"Graham Page");
		ExecID.put(5075,"Grigori");
		ExecID.put(5732,"Gruebl, Stephanie");
		ExecID.put(2158,"Guy Kemplay");
		ExecID.put(3474,"Hannah Barker");
		ExecID.put(5053,"Hannah Kilshaw");
		ExecID.put(3006,"Hannah Mills");
		ExecID.put(5666,"Haribhai, Sonal");
		ExecID.put(4411,"Harshali Patel");
		ExecID.put(1254,"HAYDN DULEY");
		ExecID.put(1665,"Hayley Miles");
		ExecID.put(3308,"Helen Kerr");
		ExecID.put(2633,"Helen Poll");
		ExecID.put(2078,"Helen Samuelson");
		ExecID.put(3320,"Helen Withers");
		ExecID.put(4467,"Henry Herbert");
		ExecID.put(5607,"Henry Karen");
		ExecID.put(6271,"Hina Ahmed");
		ExecID.put(2481,"Hitesh Chudasama");
		ExecID.put(6232,"Howie Fiona");
		ExecID.put(3856,"Hyunsook&nbsp;Yim");
		ExecID.put(3069,"Ian Beston");
		ExecID.put(6243,"Ilan.Ram");
		ExecID.put(2775,"Imran Ahmed");
		ExecID.put(4201,"Imran Fazal");
		ExecID.put(2682,"Ingrid Schluter");
		ExecID.put(5383,"Isabel Preza");
		ExecID.put(1451,"Isabella Ginnett");
		ExecID.put(2726,"Isabelle de Laveaucoupet");
		ExecID.put(2879,"Isia Nowakowska");
		ExecID.put(6344,"Isom Gemma");
		ExecID.put(1412,"Ivana Sevcu");
		ExecID.put(1099,"Jack Murray");
		ExecID.put(5294,"Jahdial Johnson");
		ExecID.put(3199,"James Ahlers");
		ExecID.put(3389,"James Burke");
		ExecID.put(2122,"James Canton");
		ExecID.put(3005,"James Dunleavy");
		ExecID.put(3497,"James Rachel");
		ExecID.put(2717,"James Wallis");
		ExecID.put(1055,"Jamie Taylor");
		ExecID.put(5281,"Janota-Bzowska, Chrissie");
		ExecID.put(2187,"Jantina Brommersma");
		ExecID.put(5324,"Jarek Cichon");
		ExecID.put(2353,"Jason Chung");
		ExecID.put(2229,"Jason De Klerk");
		ExecID.put(2692,"Jason Kok");
		ExecID.put(1648,"JAVIER MARTINEZ");
		ExecID.put(3875,"Jay Carlsen");
		ExecID.put(4354,"Jen Holmes");
		ExecID.put(1377,"Jennifer Guerreri");
		ExecID.put(4126,"Jennifer Peat");
		ExecID.put(4929,"Jeremy Weston");
		ExecID.put(1086,"Jessica Low");
		ExecID.put(2643,"Jessica Moran");
		ExecID.put(5513,"Jessica Pirbay");
		ExecID.put(4110,"Jo Hill");
		ExecID.put(4996,"Jo Knudsen");
		ExecID.put(5333,"Joanna Jocobson");
		ExecID.put(1611,"Joanna Larkin");
		ExecID.put(3859,"Joanna Masini");
		ExecID.put(4495,"Joanne Wigley");
		ExecID.put(3131,"Joanne Woolmer");
		ExecID.put(5116,"Jocelyn Woodford");
		ExecID.put(1471,"Joel Keane");
		ExecID.put(1375,"John Tearle");
		ExecID.put(4358,"Jon Allison");
		ExecID.put(3400,"Jonathan Harrison");
		ExecID.put(5980,"Jonathan Kennett,");
		ExecID.put(1656,"Juan Ramón Castillo");
		ExecID.put(3886,"Julia Dimitrova");
		ExecID.put(2705,"Julia Harrison");
		ExecID.put(4724,"Julie Cooper");
		ExecID.put(943,"Julie Law");
		ExecID.put(943,"Julie Law");
		ExecID.put(2433,"Juliette MARGERAND");
		ExecID.put(3295,"Julina Khan");
		ExecID.put(3774,"Justin Marshall");
		ExecID.put(3065,"Kalsch, Liz");
		ExecID.put(3278,"Karen Alexander");
		ExecID.put(1876,"Karen Atkins");
		ExecID.put(6241,"Karina Haines");
		ExecID.put(5202,"Katalin Nagy");
		ExecID.put(2630,"Kate Wade Lehman");
		ExecID.put(2200,"Katherine DiPrincipe");
		ExecID.put(1556,"Katherine Lodge");
		ExecID.put(2087,"Katherine McIsaac");
		ExecID.put(6324,"Kathleen Deighan");
		ExecID.put(3303,"Katie Buckley");
		ExecID.put(2362,"Katie Linshits");
		ExecID.put(2362,"Katie Linshits");
		ExecID.put(2520,"Katie Lu");
		ExecID.put(3912,"Katie Walker");
		ExecID.put(2227,"Katrina Anderson");
		ExecID.put(2276,"Katy Bridgens");
		ExecID.put(6135,"Kavan Bains");
		ExecID.put(1139,"Kay Kotak");
		ExecID.put(3483,"Kayleigh Rich");
		ExecID.put(4269,"Keith Bolling");
		ExecID.put(5947,"Kendrick Zoe");
		ExecID.put(1928,"Kevin Evans");
		ExecID.put(4356,"Kevin Hart");
		ExecID.put(4707,"Kimberley Lambert");
		ExecID.put(2912,"Kira Kanthak");
		ExecID.put(2244,"Kirsty Macmillan");
		ExecID.put(5385,"Lara Lorena");
		ExecID.put(3634,"Laura Anderson");
		ExecID.put(5242,"Laura Johnson");
		ExecID.put(5760,"Lauren Thomsen Moore");
		ExecID.put(4831,"Lauren Pratt");
		ExecID.put(1532,"Laurence Smith");
		ExecID.put(1018,"Lee Appleton");
		ExecID.put(2449,"Leon Page");
		ExecID.put(3362,"Leonoor Krijnen");
		ExecID.put(3362,"Leonoor Krijnen");
		ExecID.put(2349,"Liam Corry");
		ExecID.put(1202,"Lisa Scattergood");
		ExecID.put(2565,"Lisha Archar");
		ExecID.put(3109,"Liz Bellchambers");
		ExecID.put(3184,"Liz Mclean");
		ExecID.put(4284,"Liz Sposato");
		ExecID.put(5271,"Loes Alink");
		ExecID.put(2566,"Louisa Metherell");
		ExecID.put(1598,"Louise Bailey");
		ExecID.put(5665,"Louise Crichton");
		ExecID.put(1693,"Louise Hall");
		ExecID.put(5054,"Louise Hazell");
		ExecID.put(4187,"Louise Livesay");
		ExecID.put(2936,"Louise Stockwell");
		ExecID.put(2495,"Louise Templeman");
		ExecID.put(2495,"Louise Templeman");
		ExecID.put(1087,"Lucie Martin");
		ExecID.put(4144,"Lucy Jakeways");
		ExecID.put(3739,"Lucy Travaglia");
		ExecID.put(1023,"Luke Taylor");
		ExecID.put(2226,"Lydia Fuller");
		ExecID.put(4169,"Mads Lindegaard");
		ExecID.put(2808,"Maeve ODwyer");
		ExecID.put(6202,"Magheru, Raul");
		ExecID.put(2298,"Malgorzata Stelmach");
		ExecID.put(1041,"Manesh Luthra");
		ExecID.put(1441,"Manjit Gill");
		ExecID.put(4220,"Manolis Koumantaros");
		ExecID.put(6530,"Mansfield, Paul");
		ExecID.put(4391,"Manuel Moreno");
		ExecID.put(3046,"Manuella Barbe");
		ExecID.put(5232,"maresa Ceaser");
		ExecID.put(4566,"Marios Nicolaou");
		ExecID.put(1557,"Mark Fisher");
		ExecID.put(6292,"Mark Huitson");
		ExecID.put(965,"Martin Vovk");
		ExecID.put(2771,"Mary-Ann Parlato");
		ExecID.put(1242,"Matissa Carter");
		ExecID.put(2909,"Matt Gavin");
		ExecID.put(1687,"Matt Webster");
		ExecID.put(5198,"matthew Downer");
		ExecID.put(5198,"matthew Downer");
		ExecID.put(2596,"Matthew Fletcher");
		ExecID.put(2596,"Matthew Fletcher");
		ExecID.put(1232,"Matthew Goodwin");
		ExecID.put(5370,"matthew heckroodt");
		ExecID.put(1187,"Matthew Webster");
		ExecID.put(4653,"Matthew Woolgar");
		ExecID.put(1447,"Max Wright");
		ExecID.put(5317,"megan stodel");
		ExecID.put(4734,"Melanie Cameron");
		ExecID.put(2470,"Melissa Wilson");
		ExecID.put(4658,"Michael Bates");
		ExecID.put(3336,"Michael Chan");
		ExecID.put(5233,"Michael Liddle");
		ExecID.put(2621,"Michael Lutzenberger");
		ExecID.put(2182,"Michael Murphy");
		ExecID.put(1136,"Michael Potts");
		ExecID.put(5507,"Michael Preston");
		ExecID.put(5507,"Michael Preston");
		ExecID.put(3150,"Michael Stone");
		ExecID.put(3290,"Michelle Gray");
		ExecID.put(4482,"Michelle Hesse");
		ExecID.put(2618,"Michelle Vallinga");
		ExecID.put(3082,"Mike");
		ExecID.put(3154,"Mikhail Arutyunov");
		ExecID.put(4559,"Miles King");
		ExecID.put(3318,"Milnes Sally");
		ExecID.put(5316,"Monika Gorasia");
		ExecID.put(5380,"Monisha Saple");
		ExecID.put(6181,"Moroney Daniel");
		ExecID.put(5191,"Mroczek, Annalise");
		ExecID.put(4016,"Nadija Saluwadana");
		ExecID.put(2288,"Naomi Clench");
		ExecID.put(4304,"Naomi Winchurch");
		ExecID.put(2000,"Natalie Thomas");
		ExecID.put(3810,"Natasha Rana");
		ExecID.put(6540,"Newton, Sarah");
		ExecID.put(1714,"Nicholas Fitzgerald");
		ExecID.put(5265,"nicholas Holden");
		ExecID.put(5829,"Nick Francis");
		ExecID.put(3545,"Nick Snowdon");
		ExecID.put(5280,"nicola scobell");
		ExecID.put(1531,"Nicola Warrington");
		ExecID.put(1906,"Nicole Duckworth");
		ExecID.put(1092,"Nienke Smit");
		ExecID.put(3842,"Nikki Feld");
		ExecID.put(2905,"NILAM JANI");
		ExecID.put(3933,"Nina Kiesel");
		ExecID.put(1801,"Nuria Ayanz");
		ExecID.put(2867,"Olga Duggan");
		ExecID.put(4655,"Olga Loseva");
		ExecID.put(5342,"Oliver Armstrong");
		ExecID.put(3653,"Oliver Kempski");
		ExecID.put(4279,"Oliver Reid");
		ExecID.put(3151,"Olivia Nixson");
		ExecID.put(1901,"Olivier Bardin");
		ExecID.put(5099,"Pam M");
		ExecID.put(5932,"Patrick");
		ExecID.put(1409,"Paul Baker");
		ExecID.put(2645,"Paul Pierson");
		ExecID.put(3023,"Paul Welsby");
		ExecID.put(3503,"Paula Leonard");
		ExecID.put(1927,"Penny Bowden");
		ExecID.put(1442,"Penny Sanders");
		ExecID.put(5251,"Peter Glover");
		ExecID.put(4647,"Peter Kent");
		ExecID.put(4056,"Peter Strachan");
		ExecID.put(991,"Peter White");
		ExecID.put(4072,"Petra Bobrowski-Krüger");
		ExecID.put(1514,"Phil McCann");
		ExecID.put(2224,"Philip Carden");
		ExecID.put(1679,"Philip Cox");
		ExecID.put(4659,"Philippa Edward");
		ExecID.put(4466,"Philippa Edwards");
		ExecID.put(4466,"Philippa Edwards");
		ExecID.put(966,"Phillip Carman");
		ExecID.put(3496,"Phillipa Horsman");
		ExecID.put(4250,"Piers Tanner");
		ExecID.put(6689,"PR, Priju");
		ExecID.put(4855,"Rachel Phillips");
		ExecID.put(6242,"Raciunaite, Migle");
		ExecID.put(5038,"Rafal Charlinski");
		ExecID.put(5449,"raj Chandarana");
		ExecID.put(2020,"Ramila Mehta");
		ExecID.put(4960,"Ramona Daniel");
		ExecID.put(4136,"Ranjiv Gill");
		ExecID.put(5886,"Rasheed Giwa");
		ExecID.put(1682,"Rebeca Dreicon");
		ExecID.put(2391,"Rebecca Brooks");
		ExecID.put(3564,"Rebecca Featherstone");
		ExecID.put(3417,"Rebecca Smith");
		ExecID.put(6272,"Reeta Motiani");
		ExecID.put(4916,"Reg Fegredo");
		ExecID.put(987,"Rene Plewe");
		ExecID.put(2310,"Reshma Harjani");
		ExecID.put(5169,"Rhule Elaine");
		ExecID.put(1072,"Richard Brind");
		ExecID.put(4101,"Richard Coombe");
		ExecID.put(2294,"Robert Chow");
		ExecID.put(1596,"Robin George");
		ExecID.put(6587,"Robinson");
		ExecID.put(2728,"ROLLAND D ERCEVILLE Sophie");
		ExecID.put(3026,"Ronald Bosch");
		ExecID.put(1820,"Rory Partis");
		ExecID.put(4530,"Ross Galloway");
		ExecID.put(6327,"Roumiana Natcheva");
		ExecID.put(3877,"Russell Bradshaw");
		ExecID.put(4794,"Ruth Moyer");
		ExecID.put(1178,"Sadia Pires");
		ExecID.put(2173,"Sakina Dhalabhoy");
		ExecID.put(2599,"Sally Bussell");
		ExecID.put(6290,"Sally Chen");
		ExecID.put(3907,"Sam Curtis");
		ExecID.put(5212,"SamirCordell");
		ExecID.put(4017,"Samuel Carter");
		ExecID.put(1902,"SARA MARTINEZ");
		ExecID.put(2866,"Sara Reid");
		ExecID.put(1717,"Sarah Baillie");
		ExecID.put(2260,"Sarah Guest");
		ExecID.put(2614,"Sarah S");
		ExecID.put(4554,"Saurav Guhathakurta");
		ExecID.put(2306,"Scott Barlow");
		ExecID.put(6593,"Scottoni, Veronica");
		ExecID.put(4344,"Seabrook, Matthew");
		ExecID.put(4344,"Seabrook, Matthew");
		ExecID.put(1188,"Sean Wright");
		ExecID.put(1180,"SENGTHONG Michele");
		ExecID.put(2119,"Sharmini Choudhury");
		ExecID.put(1637,"Sharon Fergus");
		ExecID.put(1707,"Sharon Spargo");
		ExecID.put(1384,"Shaun Wilson");
		ExecID.put(2356,"Sheena Thakrar");
		ExecID.put(1026,"Shehnaz Hansraj");
		ExecID.put(1026,"Shehnaz Hansraj");
		ExecID.put(5501,"Shoun Wilson");
		ExecID.put(5399,"Shrujal Desai");
		ExecID.put(2706,"Sian Kerr");
		ExecID.put(1279,"Sian Llewellyn-Thomas");
		ExecID.put(4060,"Simon Coates");
		ExecID.put(2860,"Simon Lincoln");
		ExecID.put(4767,"Simon ODonnell");
		ExecID.put(1487,"Simon Wood");
		ExecID.put(4552,"SINAN FAHLIOGULLARI");
		ExecID.put(6532,"Sneddon Shelly");
		ExecID.put(5738,"Sonal Haribhai");
		ExecID.put(5613,"sophie dowdell");
		ExecID.put(4836,"Sophie Harding-Rolls");
		ExecID.put(2352,"Sophie Larcombe");
		ExecID.put(5887,"Sophie.Girle");
		ExecID.put(6262,"Sparks, Tim");
		ExecID.put(3938,"Stephanie Wearne");
		ExecID.put(2738,"Stephen Candlish");
		ExecID.put(4993,"Stephen Mcaree");
		ExecID.put(3230,"Stephen McGinigal");
		ExecID.put(3162,"STEPHEN OBRIEN");
		ExecID.put(3162,"STEPHEN OBRIEN");
		ExecID.put(5892,"Steve");
		ExecID.put(2900,"Steve Chamberlain");
		ExecID.put(3700,"Steve S");
		ExecID.put(4174,"Steve Seager");
		ExecID.put(1368,"Steve Thomas");
		ExecID.put(4228,"Stoetzel Petra");
		ExecID.put(1382,"Susan Pinkney");
		ExecID.put(1382,"Susan Pinkney");
		ExecID.put(1005,"Susannah McInnes");
		ExecID.put(3197,"Susie Smyth");
		ExecID.put(3660,"Swagata Sen");
		ExecID.put(6397,"Tanya Chankova");
		ExecID.put(2075,"TARTOUR Karen");
		ExecID.put(6203,"Temida Marinova");
		ExecID.put(4484,"TERRY HENMAN");
		ExecID.put(1767,"Thomas Duret");
		ExecID.put(1440,"Thomas Hotch");
		ExecID.put(1624,"Thomas Oda");
		ExecID.put(2086,"Tim Gittins");
		ExecID.put(5231,"Toby Rivers");
		ExecID.put(4355,"Todd Deye");
		ExecID.put(4348,"Tom Baynton");
		ExecID.put(4957,"Tom Cantle");
		ExecID.put(3323,"Tom Cole");
		ExecID.put(2603,"Tom Costley");
		ExecID.put(4032,"Tom Greenwood");
		ExecID.put(3905,"Tom Scrimgour");
		ExecID.put(5312,"Tony Sobrado");
		ExecID.put(3311,"Ugo Jacquemier");
		ExecID.put(6244,"Veronica Scottoni");
		ExecID.put(1025,"Vicky Wilson");
		ExecID.put(1926,"Victor Moyano");
		ExecID.put(2980,"Victoria Edmonds");
		ExecID.put(6442,"Victoria Stephens");
		ExecID.put(5218,"Vincent Pat");
		ExecID.put(2327,"Virginia Gaka");
		ExecID.put(1867,"VIRGINIA SÁNCHEZ");
		ExecID.put(1644,"Vishal Badiani");
		ExecID.put(2727,"Wayne Masters");
		ExecID.put(1297,"Wikstrom Jan");
		ExecID.put(3713,"William Nevitt");
		ExecID.put(5979,"Williams, Sarah");
		ExecID.put(4868,"Xavier Faux");
		ExecID.put(1881,"Yoanna Ilieva");
		ExecID.put(3143,"Yokey Chan");
		ExecID.put(4991,"Zoe Wilson");
//======================================================================
		StudyTypeID.put(5,"");
		StudyTypeID.put(154,"AdEval");
		StudyTypeID.put(1,"Adhoc");
		StudyTypeID.put(146,"CM");
		StudyTypeID.put(2,"Continuous/Tracker");
		StudyTypeID.put(261,"IClick");
		StudyTypeID.put(258,"Infoscore");
		StudyTypeID.put(144,"Miriad");
		StudyTypeID.put(143,"MM");
		StudyTypeID.put(3,"MS Jobs");
		StudyTypeID.put(145,"Ncompass");
		StudyTypeID.put(4,"Omnibus");
		StudyTypeID.put(155,"Others");
		StudyTypeID.put(361,"RDS");
		StudyTypeID.put(165,"SPSS");
		StudyTypeID.put(194,"Syndicated");
		StudyTypeID.put(279,"Trim - Quantum");
		StudyTypeID.put(147,"Trim - Standard Analysis");
		StudyTypeID.put(278,"Trim - TCR");

		
		referenceData.put("OfficeIDList", OfficeID);
		referenceData.put("JobTypeList", JobType);
		referenceData.put("JobOwnerList", JobOwner);
		referenceData.put("ProgressIDList", ProgressID);
		referenceData.put("ExecIDList", ExecID);
		referenceData.put("StudyTypeIDList", StudyTypeID);
		
		return referenceData;
	}
}






